# PARTE 18: OPERAR LOS DATOS DE UN DATASET

In [35]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

## PARTE 18.1: GENERAR UN SUBCONJUNTO DE COLUMNAS

In [36]:
DATASET_1_COL = DATASET[["State"]].copy().reset_index()
DATASET_1_COL.head()

   index State
0      0    KS
1      1    OH
2      2    NJ
3      3    OH
4      4    OK

In [37]:
DATASET_MAS_COL = DATASET[["State","Area code","Account length"]].copy().reset_index()
DATASET_MAS_COL.head()

   index State  Area code  Account length
0      0    KS        415             128
1      1    OH        415             107
2      2    NJ        415             137
3      3    OH        408              84
4      4    OK        415              75

In [38]:
LISTA = ['Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge']

DATASET_NUEVO = DATASET[LISTA].copy().reset_index()
DATASET_NUEVO.head()

,index,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge
0,0,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70
1,1,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70
2,2,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29
3,3,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78
4,4,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73

## PARTE 18.2: SUBCONJUNTO DE FILAS MEDIANTE SLICING

In [39]:
#FILAS EN PARTICULAR
DATASET_FILTRADO = DATASET[100:120].copy().reset_index()
DATASET_FILTRADO.head()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,100,MS,193,415,No,No,0,170.9,124,29.05,...,95,11.25,112.9,89,5.08,11.6,3,3.13,1,False
1,101,NV,130,510,No,No,0,154.2,119,26.21,...,98,9.37,227.4,117,10.23,9.2,5,2.48,2,False
2,102,AZ,85,408,No,No,0,201.4,52,34.24,...,104,19.50,252.5,106,11.36,12.0,3,3.24,1,False
3,103,MS,162,415,No,No,0,70.7,108,12.02,...,87,13.39,154.8,82,6.97,9.1,3,2.46,4,True
4,104,MS,61,510,No,Yes,27,187.5,124,31.88,...,103,12.46,225.7,129,10.16,6.4,6,1.73,4,True

In [40]:
#FILAS DESDE EL INICIO
DATASET_FILTRADO = DATASET[:20].copy().reset_index()
DATASET_FILTRADO.head()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,1,OH,107,415,No,Yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,2,NJ,137,415,No,No,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,3,OH,84,408,Yes,No,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,4,OK,75,415,Yes,No,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [41]:
#FILAS HASTA EL FINAL
DATASET_FILTRADO = DATASET[2600:].copy().reset_index()
DATASET_FILTRADO.head()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,2600,OH,160,415,No,No,0,206.3,66,35.07,...,109,20.49,227.8,102,10.25,11.7,6,3.16,0,False
1,2601,NM,55,415,No,No,0,132.0,103,22.44,...,114,23.77,180.0,74,8.10,13.5,4,3.65,0,False
2,2602,OH,88,408,No,No,0,274.6,105,46.68,...,121,13.69,194.4,123,8.75,9.2,4,2.48,2,False
3,2603,MI,63,510,No,No,0,185.3,87,31.50,...,87,19.15,194.3,93,8.74,11.7,3,3.16,0,False
4,2604,IL,57,415,No,Yes,30,179.2,105,30.46,...,83,24.07,228.1,77,10.26,14.7,5,3.97,1,False

In [42]:
#FILAS TOTALES
DATASET_FILTRADO = DATASET[:].copy().reset_index()
#DATASET_FILTRADO = DATASET.copy()
DATASET_FILTRADO.head()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,1,OH,107,415,No,Yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,2,NJ,137,415,No,No,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,3,OH,84,408,Yes,No,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,4,OK,75,415,Yes,No,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

## PARTE 18.3: SUBCONJUNTO DE FILAS MEDIANTE CONDICIONES

In [43]:
#1 CONDICIÓN 
DATASET_COND = DATASET[DATASET["State"] == "KS"].copy().reset_index()
DATASET_COND.head()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,145,KS,70,408,No,No,0,232.1,122,39.46,...,112,24.85,201.2,112,9.05,0.0,0,0.00,3,False
2,231,KS,137,408,No,No,0,205.9,88,35.00,...,86,17.79,289.9,84,13.05,14.5,4,3.92,2,False
3,299,KS,132,415,No,No,0,83.4,110,14.18,...,137,19.74,146.7,114,6.60,7.6,5,2.05,1,False
4,308,KS,127,415,No,No,0,221.0,100,37.57,...,113,13.66,233.1,96,10.49,6.8,4,1.84,2,False

In [44]:
#2 CONDICIÓN --> OR (alt + 124)
DATASET_COND = DATASET[(DATASET["State"] == "KS") | (DATASET["Total day charge"]>40)].copy().reset_index()
DATASET_COND.head()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,2,NJ,137,415,No,No,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
2,3,OH,84,408,Yes,No,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
3,8,WV,141,415,Yes,Yes,37,258.6,84,43.96,...,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
4,28,AZ,12,408,No,No,0,249.6,118,42.43,...,119,21.45,280.2,90,12.61,11.8,3,3.19,1,True

In [45]:
#2 CONDICIÓN --> AND (alt + 38)
DATASET_COND = DATASET[(DATASET["State"] == "KS") & (DATASET["Total day charge"]>40)].copy().reset_index()
DATASET_COND

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,348,KS,46,510,No,No,0,250.3,100,42.55,...,90,22.15,195.0,104,8.78,13.3,2,3.59,2,True
2,493,KS,110,415,Yes,No,0,293.3,79,49.86,...,90,16.02,266.9,91,12.01,14.5,4,3.92,0,True
3,782,KS,110,415,Yes,Yes,27,267.9,103,45.54,...,74,22.38,178.1,106,8.01,8.3,2,2.24,1,True
4,958,KS,131,415,No,Yes,28,249.6,87,42.43,...,138,19.31,239.9,92,10.80,7.6,3,2.05,3,False
5,969,KS,24,510,No,No,0,243.0,91,41.31,...,77,15.63,184.3,109,8.29,15.3,6,4.13,0,True
6,1049,KS,126,408,No,No,0,321.3,99,54.62,...,93,14.27,193.6,106,8.71,8.0,4,2.16,1,True
7,1585,KS,93,415,No,No,0,266.0,120,45.22,...,84,11.06,165.8,63,7.46,13.1,6,3.54,3,False
8,1799,KS,128,510,No,No,0,268.1,95,45.58,...,126,10.24,220.8,121,9.94,14.4,6,3.89,2,False
9,1806,KS,148,510,No,No,0,239.3,84,40.68,...,85,16.63,232.6,104,10.47,10.9,3,2.94,1,False
10,2125,KS,91,408,Yes,No,0,246.4,110,41.89,...,98,15.47,157.6,106,7.09,12.1,2,3.27,2,True
11,2317,KS,107,415,No,No,0,260.5,108,44.29,...,110,8.70,129.7,148,5.84,9.8,5,2.65,1,False
12,2579,KS,164,510,No,Yes,30,238.8,100,40.60,...,121,19.55,206.3,66,9.28,13.2,8,3.56,1,False

In [46]:
#NOT
DATASET_COND = DATASET[(DATASET["State"] != "KS")].copy().reset_index()
DATASET_COND

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,1,OH,107,415,No,Yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
1,2,NJ,137,415,No,No,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
2,3,OH,84,408,Yes,No,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
3,4,OK,75,415,Yes,No,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
4,5,AL,118,510,Yes,No,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,2661,SC,79,415,No,No,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
2610,2662,AZ,192,415,No,Yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
2611,2663,WV,68,415,No,No,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
2612,2664,RI,28,510,No,No,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
2613,2665,TN,74,415,No,Yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

## PARTE 18.4: SUBCONJUNTO DE FIL Y COL MEDIANTE ILOC

In [47]:
#[SLICING FILAS,SLICING DE COLUMNAS]
DATASET_ILOC = DATASET.iloc[ :100 , 5: ].copy().reset_index()
DATASET_ILOC

,index,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,2,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,3,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,4,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0,282.5,114,48.03,219.9,48,18.69,170.0,115,7.65,9.4,4,2.54,1,True
96,96,36,113.7,117,19.33,157.5,82,13.39,177.6,118,7.99,10.0,3,2.70,2,False
97,97,0,210.2,92,35.73,227.3,77,19.32,200.1,116,9.00,13.1,7,3.54,1,False
98,98,22,213.8,102,36.35,141.8,86,12.05,142.2,123,6.40,7.2,3,1.94,0,False
99,99,0,190.7,103,32.42,183.5,117,15.60,220.8,103,9.94,9.8,4,2.65,3,False

In [48]:
#[SLICING FILAS,SLICING DE COLUMNAS]
DATASET_ILOC = DATASET.iloc[ : , : ].copy().reset_index()
DATASET_ILOC

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,1,OH,107,415,No,Yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,2,NJ,137,415,No,No,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,3,OH,84,408,Yes,No,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,4,OK,75,415,Yes,No,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,2661,SC,79,415,No,No,0,134.7,98,22.90,...,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
2662,2662,AZ,192,415,No,Yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
2663,2663,WV,68,415,No,No,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
2664,2664,RI,28,510,No,No,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
2665,2665,TN,74,415,No,Yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

## PARTE 18.5: SUBCONJUNTO DE FIL Y COL MEDIANTE LOC

In [49]:
#[LISTA DE FILAS],[LISTA DE COLUMNAS]
DATASET_LOC = DATASET.loc[[100,300,500],['Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes']].copy().reset_index()
DATASET_LOC

,index,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes
0,100,29.05,132.3,95,11.25,112.9
1,300,33.25,267.8,120,22.76,164.9
2,500,19.16,217.7,109,18.50,152.1

## PARTE 18.6: GENERACIÓN DE UNA NUEVA COLUMNA

In [1]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

#### CÁLCULO SIMPLE

In [2]:
DATASET["N1"] = DATASET["Number vmail messages"] + 5
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,N1
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,16.78,244.7,91,11.01,10.0,3,2.70,1,False,30
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,16.62,254.4,103,11.45,13.7,3,3.70,1,False,31
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,10.30,162.6,104,7.32,12.2,5,3.29,0,False,5
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,5.26,196.9,89,8.86,6.6,7,1.78,2,False,5
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,12.61,186.9,121,8.41,10.1,3,2.73,3,False,5

#### CÁLCULO DE VARIAS COLUMNAS

In [3]:
DATASET["N2"] = DATASET["Total day minutes"] + DATASET["Total eve minutes"] + DATASET["Total night minutes"] 
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,N1,N2
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,244.7,91,11.01,10.0,3,2.70,1,False,30,707.2
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,254.4,103,11.45,13.7,3,3.70,1,False,31,611.5
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,162.6,104,7.32,12.2,5,3.29,0,False,5,527.2
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,196.9,89,8.86,6.6,7,1.78,2,False,5,558.2
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,186.9,121,8.41,10.1,3,2.73,3,False,5,501.9

#### ASIGNACIÓN DE UNA LISTA

In [6]:
LISTA = list(range(DATASET.shape[0]))
DATASET["N3"] = LISTA
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,N1,N2,N3
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,91,11.01,10.0,3,2.70,1,False,30,707.2,0
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,103,11.45,13.7,3,3.70,1,False,31,611.5,1
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,104,7.32,12.2,5,3.29,0,False,5,527.2,2
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,89,8.86,6.6,7,1.78,2,False,5,558.2,3
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,121,8.41,10.1,3,2.73,3,False,5,501.9,4

#### EJEMPLO DE RECORRIDO

In [9]:
LISTA_CHURN = list(DATASET["Churn"])

for INDICE,VALOR in enumerate(LISTA_CHURN):
    LISTA_CHURN[INDICE] = not(VALOR)
    
DATASET["N4"] = LISTA_CHURN
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,N1,N2,N3,N4
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,11.01,10.0,3,2.70,1,False,30,707.2,0,True
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,11.45,13.7,3,3.70,1,False,31,611.5,1,True
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,7.32,12.2,5,3.29,0,False,5,527.2,2,True
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,8.86,6.6,7,1.78,2,False,5,558.2,3,True
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,8.41,10.1,3,2.73,3,False,5,501.9,4,True

## PARTE 18.7: GENERACIÓN DE UNA NUEVA FILA

In [16]:
DATASET_NUEVO = DATASET.iloc[4:15 , 2:6].copy()
DATASET_NUEVO

    Area code International plan Voice mail plan  Number vmail messages
4         415                Yes              No                      0
5         510                Yes              No                      0
6         510                 No             Yes                     24
7         415                Yes              No                      0
8         415                Yes             Yes                     37
9         415                 No              No                      0
10        408                 No              No                      0
11        510                 No              No                      0
12        415                 No              No                      0
13        408                 No             Yes                     27
14        510                 No              No                      0

In [17]:
DATASET_NUEVO_2 = DATASET_NUEVO.append(
{
    "Area code":300,
    "International plan":"No",
    "Voice mail plan":"XYZ",
    "Number vmail messages":3
},ignore_index=True
)

In [18]:
DATASET_NUEVO_2

    Area code International plan Voice mail plan  Number vmail messages
0         415                Yes              No                      0
1         510                Yes              No                      0
2         510                 No             Yes                     24
3         415                Yes              No                      0
4         415                Yes             Yes                     37
5         415                 No              No                      0
6         408                 No              No                      0
7         510                 No              No                      0
8         415                 No              No                      0
9         408                 No             Yes                     27
10        510                 No              No                      0
11        300                 No             XYZ                      3

## PARTE 18.8: GENERACIÓN DE UN DATASET

In [20]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

In [21]:
DATASET1 = DATASET.iloc[:10 , 2:6 ].copy()
DATASET1

   Area code International plan Voice mail plan  Number vmail messages
0        415                 No             Yes                     25
1        415                 No             Yes                     26
2        415                 No              No                      0
3        408                Yes              No                      0
4        415                Yes              No                      0
5        510                Yes              No                      0
6        510                 No             Yes                     24
7        415                Yes              No                      0
8        415                Yes             Yes                     37
9        415                 No              No                      0

In [23]:
DATASET2 = DATASET.iloc[:10 , 6:12].copy()
DATASET2

,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge
0,265.1,110,45.07,197.4,99,16.78
1,161.6,123,27.47,195.5,103,16.62
2,243.4,114,41.38,121.2,110,10.30
3,299.4,71,50.90,61.9,88,5.26
4,166.7,113,28.34,148.3,122,12.61
5,223.4,98,37.98,220.6,101,18.75
6,218.2,88,37.09,348.5,108,29.62
7,157.0,79,26.69,103.1,94,8.76
8,258.6,84,43.96,222.0,111,18.87
9,187.7,127,31.91,163.4,148,13.89

#### CON COLUMNAS DE 1 DATASET

In [25]:
DATASET_GENERADO_1 = pd.DataFrame(
{
    "COL1":DATASET1["Area code"],
    "COL2":DATASET1["Number vmail messages"]
})

DATASET_GENERADO_1

   COL1  COL2
0   415    25
1   415    26
2   415     0
3   408     0
4   415     0
5   510     0
6   510    24
7   415     0
8   415    37
9   415     0

#### CON COLUMNAS DE VARIOS DATASET

In [27]:
DATASET_GENERADO_2 = pd.DataFrame(
{
    "COL1":DATASET1["Area code"],
    "COL2":DATASET1["Number vmail messages"],
    "COL3":DATASET2["Total day minutes"],
    "COL4":DATASET2["Total day calls"]
})

DATASET_GENERADO_2

   COL1  COL2   COL3  COL4
0   415    25  265.1   110
1   415    26  161.6   123
2   415     0  243.4   114
3   408     0  299.4    71
4   415     0  166.7   113
5   510     0  223.4    98
6   510    24  218.2    88
7   415     0  157.0    79
8   415    37  258.6    84
9   415     0  187.7   127

#### CON COLUMNAS DE VARIOS DATASET Y LISTA

In [28]:
LISTA = list(range(DATASET1.shape[0]))

DATASET_GENERADO_3 = pd.DataFrame(
{
    "COL1":DATASET1["Area code"],
    "COL2":DATASET1["Number vmail messages"],
    "COL3":DATASET2["Total day minutes"],
    "COL4":DATASET2["Total day calls"],
    "COL5":LISTA
})

DATASET_GENERADO_3

   COL1  COL2   COL3  COL4  COL5
0   415    25  265.1   110     0
1   415    26  161.6   123     1
2   415     0  243.4   114     2
3   408     0  299.4    71     3
4   415     0  166.7   113     4
5   510     0  223.4    98     5
6   510    24  218.2    88     6
7   415     0  157.0    79     7
8   415    37  258.6    84     8
9   415     0  187.7   127     9

## PARTE 18.9: ORDENAR UN DATASET

In [29]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

In [32]:
DATASET_ORDENADO_1 = DATASET.sort_values(["Total day minutes"], ascending = True).copy().reset_index()
DATASET_ORDENADO_1

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,1100,VT,101,510,No,No,0,0.0,0,0.00,...,119,16.33,168.8,95,7.60,7.2,4,1.94,1,False
1,1057,SD,98,415,No,No,0,0.0,0,0.00,...,130,13.57,167.1,88,7.52,6.8,1,1.84,4,True
2,2206,OK,127,510,No,Yes,27,2.6,113,0.44,...,102,21.59,242.7,156,10.92,9.2,5,2.48,3,False
3,2218,OH,134,415,No,No,0,7.8,86,1.33,...,100,14.57,186.5,80,8.39,12.9,2,3.48,2,False
4,1575,WI,70,415,No,No,0,7.9,100,1.34,...,83,11.59,156.6,89,7.05,12.1,1,3.27,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,485,MO,112,415,No,No,0,335.5,77,57.04,...,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True
2662,128,OH,83,415,No,No,0,337.4,120,57.36,...,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True
2663,2087,OH,115,510,Yes,No,0,345.3,81,58.70,...,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True
2664,780,NY,64,415,Yes,No,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True
2665,296,CO,154,415,No,No,0,350.8,75,59.64,...,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True

In [33]:
DATASET_ORDENADO_2 = DATASET.sort_values(["Total day minutes"], ascending = False).copy().reset_index()
DATASET_ORDENADO_2

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,296,CO,154,415,No,No,0,350.8,75,59.64,...,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True
1,780,NY,64,415,Yes,No,0,346.8,55,58.96,...,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True
2,2087,OH,115,510,Yes,No,0,345.3,81,58.70,...,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True
3,128,OH,83,415,No,No,0,337.4,120,57.36,...,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True
4,485,MO,112,415,No,No,0,335.5,77,57.04,...,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,1575,WI,70,415,No,No,0,7.9,100,1.34,...,83,11.59,156.6,89,7.05,12.1,1,3.27,0,False
2662,2218,OH,134,415,No,No,0,7.8,86,1.33,...,100,14.57,186.5,80,8.39,12.9,2,3.48,2,False
2663,2206,OK,127,510,No,Yes,27,2.6,113,0.44,...,102,21.59,242.7,156,10.92,9.2,5,2.48,3,False
2664,1100,VT,101,510,No,No,0,0.0,0,0.00,...,119,16.33,168.8,95,7.60,7.2,4,1.94,1,False
2665,1057,SD,98,415,No,No,0,0.0,0,0.00,...,130,13.57,167.1,88,7.52,6.8,1,1.84,4,True

In [35]:
DATASET_ORDENADO_3 = DATASET.sort_values(["State","Total day minutes"], ascending = True).copy().reset_index()
DATASET_ORDENADO_3

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,147,AK,126,415,No,No,0,58.2,94,9.89,...,118,11.79,136.8,91,6.16,11.9,1,3.21,5,True
1,1826,AK,138,415,No,Yes,37,75.8,102,12.89,...,147,14.76,162.6,96,7.32,8.2,13,2.21,0,False
2,1114,AK,141,408,No,No,0,83.2,74,14.14,...,104,16.20,150.5,79,6.77,10.7,7,2.89,1,False
3,755,AK,108,415,No,No,0,103.0,129,17.51,...,103,20.60,170.2,89,7.66,7.9,3,2.13,1,False
4,640,AK,156,510,No,No,0,123.7,96,21.03,...,80,8.76,189.4,82,8.52,13.1,4,3.54,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,990,WY,95,415,No,Yes,39,260.8,130,44.34,...,111,18.14,195.6,97,8.80,10.1,5,2.73,1,False
2662,807,WY,76,415,No,No,0,263.4,148,44.78,...,69,19.58,170.6,101,7.68,11.4,5,3.08,1,True
2663,521,WY,87,415,No,Yes,22,263.8,65,44.85,...,115,8.79,208.1,109,9.36,8.5,3,2.30,3,False
2664,894,WY,106,415,Yes,Yes,26,270.3,111,45.95,...,90,18.29,254.0,133,11.43,14.4,7,3.89,1,True
2665,571,WY,94,510,No,No,0,271.2,105,46.10,...,105,17.22,221.6,51,9.97,11.5,3,3.11,3,True

## PARTE 18.10: TRANSFORMAR UN DATASET

In [37]:
AUMENTAR_1 = lambda X : X + 1

NEGAR = lambda X : not(X)

In [40]:
DATASET["N1"] = DATASET["Customer service calls"].transform(AUMENTAR_1)
DATASET

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,N1
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,16.78,244.7,91,11.01,10.0,3,2.70,1,False,2
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,16.62,254.4,103,11.45,13.7,3,3.70,1,False,2
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,10.30,162.6,104,7.32,12.2,5,3.29,0,False,1
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,5.26,196.9,89,8.86,6.6,7,1.78,2,False,3
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,12.61,186.9,121,8.41,10.1,3,2.73,3,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,No,No,0,134.7,98,22.90,189.7,...,16.12,221.4,128,9.96,11.8,5,3.19,2,False,3
2662,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,...,18.32,279.1,83,12.56,9.9,6,2.67,2,False,3
2663,WV,68,415,No,No,0,231.1,57,39.29,153.4,...,13.04,191.3,123,8.61,9.6,4,2.59,3,False,4
2664,RI,28,510,No,No,0,180.8,109,30.74,288.8,...,24.55,191.9,91,8.64,14.1,6,3.81,2,False,3
2665,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,...,22.60,241.4,77,10.86,13.7,4,3.70,0,False,1

In [41]:
DATASET["N2"] = DATASET["Churn"].transform(NEGAR)
DATASET

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,N1,N2
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,244.7,91,11.01,10.0,3,2.70,1,False,2,True
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,254.4,103,11.45,13.7,3,3.70,1,False,2,True
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,162.6,104,7.32,12.2,5,3.29,0,False,1,True
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,196.9,89,8.86,6.6,7,1.78,2,False,3,True
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,186.9,121,8.41,10.1,3,2.73,3,False,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,No,No,0,134.7,98,22.90,189.7,...,221.4,128,9.96,11.8,5,3.19,2,False,3,True
2662,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,...,279.1,83,12.56,9.9,6,2.67,2,False,3,True
2663,WV,68,415,No,No,0,231.1,57,39.29,153.4,...,191.3,123,8.61,9.6,4,2.59,3,False,4,True
2664,RI,28,510,No,No,0,180.8,109,30.74,288.8,...,191.9,91,8.64,14.1,6,3.81,2,False,3,True
2665,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,...,241.4,77,10.86,13.7,4,3.70,0,False,1,True

## PARTE 18.11: ELIMINAR FILAS EN UN DATASET

* AXIS = 0 --> FILAS
* DEBES PROPORCIONAR LOS ÍNDICES DE LAS FILAS

In [42]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

#### ELIMINACIÓN MEDIANTE LISTA

In [44]:
DATASET_ELIMINADO = DATASET.drop([1,3,5] , axis = 0)
DATASET_ELIMINADO.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False
10,IA,168,408,No,No,0,128.8,96,21.90,104.9,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False
11,MT,95,510,No,No,0,156.6,88,26.62,247.6,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False
12,IA,62,415,No,No,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,False

#### ELIMINACIÓN MEDIANTE UN RANGO

In [45]:
DATASET_ELIMINADO = DATASET.drop(range(0,100) , axis = 0)
DATASET_ELIMINADO.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
100,MS,193,415,No,No,0,170.9,124,29.05,132.3,95,11.25,112.9,89,5.08,11.6,3,3.13,1,False
101,NV,130,510,No,No,0,154.2,119,26.21,110.2,98,9.37,227.4,117,10.23,9.2,5,2.48,2,False
102,AZ,85,408,No,No,0,201.4,52,34.24,229.4,104,19.50,252.5,106,11.36,12.0,3,3.24,1,False
103,MS,162,415,No,No,0,70.7,108,12.02,157.5,87,13.39,154.8,82,6.97,9.1,3,2.46,4,True
104,MS,61,510,No,Yes,27,187.5,124,31.88,146.6,103,12.46,225.7,129,10.16,6.4,6,1.73,4,True
105,TX,92,408,No,No,0,91.7,90,15.59,193.7,123,16.46,175.0,86,7.88,9.2,4,2.48,2,False
106,NE,131,408,No,Yes,36,214.2,115,36.41,161.7,117,13.74,264.7,102,11.91,9.5,4,2.57,3,False
107,NE,90,415,No,No,0,145.5,92,24.74,217.7,114,18.50,146.9,123,6.61,10.9,2,2.94,3,False
108,NJ,78,415,No,No,0,231.0,115,39.27,230.4,140,19.58,261.4,120,11.76,9.5,3,2.57,1,False
109,TX,82,408,No,No,0,200.3,96,34.05,201.2,102,17.10,206.1,60,9.27,7.1,1,1.92,4,False

## PARTE 18.12: ELIMINAR COLUMNAS EN UN DATASET

* AXIS = 1 --> COLUMNAS
* DEBES PROPORCIONAR LOS NOMBRES DE LAS COLUMNAS

In [46]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

In [48]:
DATASET_ELIMINADO = DATASET.drop(["State","Account length"] , axis = 1)
DATASET_ELIMINADO

,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,415,No,No,0,134.7,98,22.90,189.7,68,16.12,221.4,128,9.96,11.8,5,3.19,2,False
2662,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
2663,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
2664,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
2665,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [50]:
DATASET_ORDENADO_2 = DATASET.sort_values(["Total day minutes"], ascending = False).copy().reset_index()
DATASET_ORDENADO_2 = DATASET_ORDENADO_2.drop(["index"] , axis = 1)
DATASET_ORDENADO_2

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,CO,154,415,No,No,0,350.8,75,59.64,216.5,94,18.40,253.9,100,11.43,10.1,9,2.73,1,True
1,NY,64,415,Yes,No,0,346.8,55,58.96,249.5,79,21.21,275.4,102,12.39,13.3,9,3.59,1,True
2,OH,115,510,Yes,No,0,345.3,81,58.70,203.4,106,17.29,217.5,107,9.79,11.8,8,3.19,1,True
3,OH,83,415,No,No,0,337.4,120,57.36,227.4,116,19.33,153.9,114,6.93,15.8,7,4.27,0,True
4,MO,112,415,No,No,0,335.5,77,57.04,212.5,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,WI,70,415,No,No,0,7.9,100,1.34,136.4,83,11.59,156.6,89,7.05,12.1,1,3.27,0,False
2662,OH,134,415,No,No,0,7.8,86,1.33,171.4,100,14.57,186.5,80,8.39,12.9,2,3.48,2,False
2663,OK,127,510,No,Yes,27,2.6,113,0.44,254.0,102,21.59,242.7,156,10.92,9.2,5,2.48,3,False
2664,VT,101,510,No,No,0,0.0,0,0.00,192.1,119,16.33,168.8,95,7.60,7.2,4,1.94,1,False
2665,SD,98,415,No,No,0,0.0,0,0.00,159.6,130,13.57,167.1,88,7.52,6.8,1,1.84,4,True

## PARTE 18.13: GENERACIÓN DE VARIABLES DUMMY

In [65]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

In [54]:
COLUMNAS_DUMMY = list(DATASET.select_dtypes(include = ["object","bool"]))
COLUMNAS_DUMMY

['State', 'International plan', 'Voice mail plan', 'Churn']

In [56]:
DATASET_DUMMY_STATE = pd.get_dummies(DATASET["State"] , prefix = "STATE")
DATASET_DUMMY_STATE

,STATE_AK,STATE_AL,STATE_AR,STATE_AZ,STATE_CA,STATE_CO,STATE_CT,STATE_DC,STATE_DE,STATE_FL,...,STATE_SD,STATE_TN,STATE_TX,STATE_UT,STATE_VA,STATE_VT,STATE_WA,STATE_WI,STATE_WV,STATE_WY
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2662,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2663,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2664,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2665,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [57]:
DATASET_DUMMY_VMP = pd.get_dummies(DATASET["Voice mail plan"] , prefix = "VMP")
DATASET_DUMMY_VMP

      VMP_No  VMP_Yes
0          0        1
1          0        1
2          1        0
3          1        0
4          1        0
...      ...      ...
2661       1        0
2662       0        1
2663       1        0
2664       1        0
2665       0        1

[2666 rows x 2 columns]

In [58]:
DATASET_DUMMY_CHURN = pd.get_dummies(DATASET["Churn"] , prefix = "CHURN")
DATASET_DUMMY_CHURN

      CHURN_False  CHURN_True
0               1           0
1               1           0
2               1           0
3               1           0
4               1           0
...           ...         ...
2661            1           0
2662            1           0
2663            1           0
2664            1           0
2665            1           0

[2666 rows x 2 columns]

In [66]:
DATASET = pd.concat([DATASET, DATASET_DUMMY_CHURN] , axis = 1)
DATASET = DATASET.drop(["Churn"], axis = 1)
DATASET

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,CHURN_False,CHURN_True
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,16.78,244.7,91,11.01,10.0,3,2.70,1,1,0
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,16.62,254.4,103,11.45,13.7,3,3.70,1,1,0
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,10.30,162.6,104,7.32,12.2,5,3.29,0,1,0
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,5.26,196.9,89,8.86,6.6,7,1.78,2,1,0
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,12.61,186.9,121,8.41,10.1,3,2.73,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,No,No,0,134.7,98,22.90,189.7,...,16.12,221.4,128,9.96,11.8,5,3.19,2,1,0
2662,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,...,18.32,279.1,83,12.56,9.9,6,2.67,2,1,0
2663,WV,68,415,No,No,0,231.1,57,39.29,153.4,...,13.04,191.3,123,8.61,9.6,4,2.59,3,1,0
2664,RI,28,510,No,No,0,180.8,109,30.74,288.8,...,24.55,191.9,91,8.64,14.1,6,3.81,2,1,0
2665,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,...,22.60,241.4,77,10.86,13.7,4,3.70,0,1,0

In [67]:
DATASET = pd.concat([DATASET, DATASET_DUMMY_VMP] , axis = 1)
DATASET = DATASET.drop(["Voice mail plan"], axis = 1)
DATASET

,State,Account length,Area code,International plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,...,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,CHURN_False,CHURN_True,VMP_No,VMP_Yes
0,KS,128,415,No,25,265.1,110,45.07,197.4,99,...,91,11.01,10.0,3,2.70,1,1,0,0,1
1,OH,107,415,No,26,161.6,123,27.47,195.5,103,...,103,11.45,13.7,3,3.70,1,1,0,0,1
2,NJ,137,415,No,0,243.4,114,41.38,121.2,110,...,104,7.32,12.2,5,3.29,0,1,0,1,0
3,OH,84,408,Yes,0,299.4,71,50.90,61.9,88,...,89,8.86,6.6,7,1.78,2,1,0,1,0
4,OK,75,415,Yes,0,166.7,113,28.34,148.3,122,...,121,8.41,10.1,3,2.73,3,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,No,0,134.7,98,22.90,189.7,68,...,128,9.96,11.8,5,3.19,2,1,0,1,0
2662,AZ,192,415,No,36,156.2,77,26.55,215.5,126,...,83,12.56,9.9,6,2.67,2,1,0,0,1
2663,WV,68,415,No,0,231.1,57,39.29,153.4,55,...,123,8.61,9.6,4,2.59,3,1,0,1,0
2664,RI,28,510,No,0,180.8,109,30.74,288.8,58,...,91,8.64,14.1,6,3.81,2,1,0,1,0
2665,TN,74,415,No,25,234.4,113,39.85,265.9,82,...,77,10.86,13.7,4,3.70,0,1,0,0,1

## PARTE 18.14: AGRUPAR UN DATASET MEDIANTE UNA VARIABLE

* count-->Conteo de valores
* sum-->Suma de valores 
* mean-->Promedio de valores 
* median-->Mediana de valores 
* min-->Mínimo valor
* max-->Máximo valor
* mode-->Moda de valores
* prod-->Producto de valores
* std-->Desviación estándar
* var-->Varianza

In [4]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)

DATASET.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,No,Yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,Yes,No,0,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
9,RI,74,415,No,No,0,187.7,127,31.91,163.4,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False

In [152]:
DATASET_AGRUPADO_STATE = DATASET.groupby(["State"])
DATASET_AGRUPADO_STATE

In [156]:
#FILTRAR LA INFORMACIÓN DE UN DATASET AGRUPADO
DATASET_AGRUPADO_STATE.get_group("NJ").head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
33,NJ,149,408,No,No,0,140.4,94,23.87,271.8,92,23.10,188.3,108,8.47,11.1,9,3.00,1,False
59,NJ,138,408,No,No,0,241.8,93,41.11,170.5,83,14.49,295.3,104,13.29,11.8,7,3.19,3,False
75,NJ,128,415,No,No,0,237.9,125,40.44,247.6,93,21.05,208.9,68,9.40,13.9,4,3.75,1,True
94,NJ,64,510,No,No,0,162.6,83,27.64,152.3,109,12.95,57.5,122,2.59,14.2,3,3.83,1,False

In [175]:
#AGRUPAR LA INFORMACIÓN CON BASE EN ALGUNA FUNCIÓN
DATASET_AGRUPADO_STATE.mean()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,
AK,100.790698,442.255814,7.255814,180.132558,94.627907,30.623023,184.560465,95.558140,15.687907,192.679070,98.069767,8.670698,10.134884,4.883721,2.736279,1.511628,0.069767
AL,98.090909,429.939394,6.742424,188.372727,99.439394,32.023182,192.798485,98.075758,16.388030,185.042424,101.227273,8.326970,10.193939,4.696970,2.752273,1.666667,0.106061
AR,95.170213,437.468085,5.659574,174.695745,104.382979,29.698511,203.065957,99.787234,17.261277,201.572340,96.936170,9.071064,10.478723,4.829787,2.829362,2.148936,0.234043
AZ,103.111111,430.333333,9.044444,173.748889,101.444444,29.537556,185.053333,103.044444,15.729778,198.815556,100.466667,8.947333,10.615556,5.288889,2.866222,1.377778,0.066667
CA,100.458333,429.666667,10.375000,180.783333,100.666667,30.733750,199.179167,106.500000,16.930833,191.791667,100.125000,8.630417,10.150000,4.416667,2.742083,1.416667,0.208333
CO,101.983051,431.711864,8.186441,179.513559,94.881356,30.518136,208.579661,96.203390,17.728983,189.706780,95.576271,8.537627,9.777966,4.237288,2.640678,1.830508,0.118644
CT,94.457627,429.203390,6.338983,174.281356,98.610169,29.628136,203.991525,98.694915,17.339661,201.883051,101.915254,9.085254,9.949153,3.983051,2.686271,1.406780,0.186441
DC,105.866667,440.733333,9.155556,167.737778,97.933333,28.516222,197.697778,101.933333,16.805556,205.535556,97.000000,9.249333,10.782222,4.044444,2.912222,1.288889,0.111111
DE,99.941176,439.568627,7.254902,173.535294,98.549020,29.501961,209.711765,99.333333,17.825882,204.901961,101.705882,9.220588,10.350980,3.901961,2.795882,1.705882,0.156863
FL,109.777778,445.500000,9.500000,178.577778,99.222222,30.359259,206.142593,106.925926,17.522407,195.727778,100.740741,8.807407,9.938889,3.944444,2.683889,1.611111,0.129630
GA,100.653061,442.081633,11.040816,186.487755,104.612245,31.703673,204.273469,101.877551,17.363469,195.622449,105.795918,8.803061,10.357143,4.040816,2.797143,1.918367,0.163265
HI,105.090909,423.886364,8.704545,172.700000,101.000000,29.358182,190.920455,99.136364,16.227727,200.902273,98.295455,9.040227,10.075000,4.772727,2.720682,1.727273,0.045455
IA,94.500000,446.210526,7.500000,182.221053,104.131579,30.978684,202.544737,98.157895,17.216842,193.284211,98.736842,8.698684,9.747368,4.763158,2.632368,1.605263,0.078947
ID,102.642857,440.892857,10.392857,174.439286,108.017857,29.655179,194.644643,98.285714,16.545179,205.371429,100.392857,9.241964,10.371429,4.303571,2.800357,1.642857,0.089286
IL,101.022222,436.355556,6.800000,169.962222,101.044444,28.894889,202.617778,102.088889,17.222444,199.302222,97.311111,8.968667,10.288889,4.333333,2.778889,1.111111,0.088889
IN,101.851852,445.111111,7.259259,196.929630,105.814815,33.478889,199.359259,98.703704,16.945556,214.755556,100.388889,9.663889,9.775926,4.259259,2.639815,1.611111,0.111111
KS,105.211538,444.980769,7.115385,196.178846,100.307692,33.350962,202.917308,98.326923,17.248077,205.296154,100.384615,9.238462,10.901923,4.346154,2.944038,1.480769,0.192308
KY,93.348837,437.837209,7.790698,175.441860,99.093023,29.826047,194.406977,99.651163,16.524419,199.372093,102.720930,8.971860,10.851163,4.209302,2.930000,1.744186,0.139535
LA,110.200000,434.514286,8.257143,171.605714,102.971429,29.173143,193.802857,96.628571,16.474000,206.088571,101.628571,9.273714,9.148571,4.342857,2.471143,1.514286,0.085714
MA,91.057692,430.846154,8.596154,176.780769,101.615385,30.052885,216.250000,98.326923,18.381731,211.438462,96.730769,9.515385,9.986538,4.288462,2.696923,1.230769,0.153846
MD,101.033333,430.783333,7.750000,198.615000,97.833333,33.765333,194.415000,99.850000,16.525167,201.426667,95.600000,9.063833,10.740000,4.383333,2.900000,1.650000,0.233333
ME,99.897959,454.285714,7.551020,182.457143,100.510204,31.018776,201.148980,106.346939,17.097959,199.930612,97.306122,8.996939,9.957143,4.632653,2.689592,1.734694,0.224490
MI,101.431034,444.793103,6.965517,179.043103,99.086207,30.437241,208.812069,100.844828,17.748793,193.794828,103.603448,8.720345,10.550000,4.603448,2.848793,1.586207,0.224138
MN,103.528571,440.342857,8.742857,179.608571,98.900000,30.533857,198.757143,103.514286,16.894714,207.952857,101.642857,9.357857,10.418571,4.428571,2.813571,1.514286,0.185714
MO,103.686275,425.980392,7.960784,170.100000,99.882353,28.918235,203.794118,102.294118,17.322941,205.049020,101.372549,9.227059,10.235294,4.882353,2.764118,1.529412,0.098039
MS,103.208333,441.104167,9.583333,173.447917,102.416667,29.486667,196.972917,99.104167,16.743333,201.412500,99.791667,9.063333,10.437500,4.895833,2.818750,1.687500,0.229167
MT,90.132075,436.452830,10.075472,173.524528,95.301887,29.499245,199.288679,97.188679,16.940000,197.020755,102.547170,8.866038,10.696226,4.415094,2.888491,1.584906,0.188679
NC,103.303571,434.678571,9.410714,185.492857,103.125000,31.534286,199.871429,104.232143,16.989464,194.260714,100.464286,8.741607,10.003571,3.910714,2.701607,1.535714,0.160714
ND,107.045455,436.681818,12.090909,186.236364,100.613636,31.661136,202.361364,102.636364,17.201136,202.168182,102.636364,9.097500,9.334091,5.136364,2.521136,1.500000,0.090909
NE,100.422222,434.400000,9.488889,178.355556,94.688889,30.320222,201.860000,102.200000,17.157333,206.755556,103.444444,9.303778,10.728889,4.111111,2.897556,1.622222,0.088889
NH,102.348837,431.953488,6.627907,177.523256,101.093023,30.179070,197.834884,96.046512,16.816279,213.151163,98.302326,9.591628,10.434884,5.000000,2.817907,1.627907,0.209302
NJ,98.960000,437.880000,9.640000,199.086000,99.360000,33.844800,199.858000,101.380000,16.988000,203.962000,100.380000,9.178400,11.224000,4.800000,3.031800,1.700000,0.280000
NM,106.681818,430.204545,6.068182,173.684091,101.681818,29.526364,212.252273,102.340909,18.041818,202.263636,103.068182,9.101364,10.159091,4.795455,2.743864,1.454545,0.090909
NV,104.409836,441.770492,6.393443,177.750820,102.311475,30.218197,203.637705,95.918033,17.309344,208.237705,101.377049,9.370492,10.080328,4.213115,2.721803,1.606557,0.213115
NY,96.279412,430.014706,7.088235,172.686765,99.176471,29.357941,196.908824,100.911765,16.737353,204.125000,98.632353,9.186176,10.216176,4.764706,2.758382,1.691176,0.176471
OH,98.590909,434.575758,10.515152,184.689394,99.787879,31.398182,206.809091,101.363636,17.579091,208.325758,103.757576,9.374394,10.307576,4.439394,2.783788,1.348485,0.151515
OK,110.557692,436.730769,8.269231,180.000000,99.807692,30.600192,191.061538,105.057692,16.241154,196.678846,101.942308,8.850192,10.567308,4.769231,2.854615,1.807692,0.134615
OR,99.870968,438.048387,5.854839,170.375806,94.564516,28.964839,197.930645,98.564516,16.824677,199.708065,102.209677,8.987097,10.520968,4.403226,2.841774,1.790323,0.112903
PA,102.361111,439.444444,8.250000,196.211111,98.888889,33.356111,187.136111,100.361111,15.906111,193.302778,99.500000,8.699444,10.422222,3.583333,2.814167,1.305556,0.222222
RI,96.625000,449.604167,7.458333,174.270833,100.875000,29.627083,205.595833,93.270833,17.476042,206.770833,101.750000,9.304583,10.100000,4.479167,2.727083,1.416667,0.062500
SC,92.102041,436.693878,8.367347,162.528571,101.571429,27.630408,205.926531,100.714286,17.503265,193.306122,99.816327,8.698980,9.838776,4.102041,2.657143,1.469388,0.224490
SD,106.816327,442.510204,9.367347,191.404082,93.918367,32.538980,207.681633,98.367347,17.652653,201.644898,94.081633,9.074490,9.848980,4.306122,2.659184,1.408163,0.122449
TN,90.317073,436.634146,7.365854,182.846341,99.658537,31.084390,207.348780,105.853659,17.625122,205.580488,91.000000,9.251707,10.429268,4.243902,2.815854,1.317073,0.121951
TX,92.400000,432.090909,6.290909,181.030909,101.236364,30.776182,197.910909,101.254545,16.822727,200.496364,99.290909,9.022545,10.585455,4.709091,2.858727,1.490909,0.290909
UT,99.900000,440.633333,9.166667,183.568333,99.683333,31.207000,196.346667,97.866667,16.690000,192.546667,100.733333,8.664167,9.976667,4.616667,2.694000,1.333333,0.133333
VA,105.850746,436.805970,6.656716,179.073134,105.910448,30.442537,204.835821,100.462687,17.411791,212.667164,93.104478,9.570448,10.564179,4.671642,2.852687,1.537313,0.059701
VT,103.947368,439.947368,6.526316,183.114035,101.035088,31.130351,202.252632,96.982456,17.192105,207.229825,103.578947,9.325088,10.080702,4.736842,2.722105,1.736842,0.105263
WA,103.145833,436.125000,4.166667,175.462500,100.520833,29.829375,204.029167,95.750000,17.342708,199.016667,103.750000,8.956042,9.712500,4.520833,2.622708,1.479167,0.208333
WI,96.934426,436.409836,8.196721,175.775410,97.000000,29.881803,197.759016,99.081967,16.810000,198.313115,98.426230,8.924262,9.634426,4.114754,2.601639,1.360656,0.065574
WV,94.465909,442.954545,8.988636,172.012500,104.500000,29.242841,185.947727,99.363636,15.805455,199.531818,100.715909,8.979318,9.912500,4.375000,2.676818,1.625000,0.079545
WY,105.378788,436.439394,7.030303,179.936364,101.333333,30.589242,210.113636,99.166667,17.859697,198.271212,102.787879,8.922273,10.340909,4.924242,2.792424,1.439394,0.121212

In [164]:
#TAMAÑO DE LA CATEGORÍA
DATASET_AGRUPADO_STATE.size()

State
AK    43
AL    66
AR    47
AZ    45
CA    24
CO    59
CT    59
DC    45
DE    51
FL    54
GA    49
HI    44
IA    38
ID    56
IL    45
IN    54
KS    52
KY    43
LA    35
MA    52
MD    60
ME    49
MI    58
MN    70
MO    51
MS    48
MT    53
NC    56
ND    44
NE    45
NH    43
NJ    50
NM    44
NV    61
NY    68
OH    66
OK    52
OR    62
PA    36
RI    48
SC    49
SD    49
TN    41
TX    55
UT    60
VA    67
VT    57
WA    48
WI    61
WV    88
WY    66
dtype: int64

In [167]:
#DESCRIPCIÓN DE LA CATEGORÍA
DATASET_AGRUPADO_STATE.describe()

      Account length                                                     \
               count        mean        std   min    25%    50%     75%
State
AK              43.0  100.790698  36.946266  41.0  66.00  104.0  127.00
AL              66.0   98.090909  41.865987   8.0  78.25   95.5  121.75
AR              47.0   95.170213  34.284817   5.0  79.50   98.0  115.00
AZ              45.0  103.111111  32.676946  12.0  85.00  100.0  127.00
CA              24.0  100.458333  34.150535  33.0  80.75   99.5  117.00
CO              59.0  101.983051  38.858937  22.0  72.50  104.0  125.00
CT              59.0   94.457627  38.985551  22.0  68.50   95.0  119.50
DC              45.0  105.866667  42.654319  11.0  74.00  108.0  136.00
DE              51.0   99.941176  38.336099   2.0  76.50   99.0  119.00
FL              54.0  109.777778  32.244740  22.0  91.25  109.5  129.75
GA              49.0  100.653061  42.227337  18.0  72.00   93.0  125.00
HI              44.0  105.090909  41.164343   3.0  87.00  105.0  132.50
IA              38.0   94.500000  43.295808   1.0  62.50   93.5  127.50
ID              56.0  102.642857  39.248128  24.0  81.00   97.5  121.00
IL              45.0  101.022222  39.795208  16.0  74.00   91.0  138.00
IN              54.0  101.851852  38.245191   7.0  78.00   98.5  118.50
KS              52.0  105.211538  36.241746  24.0  77.50  110.0  130.25
KY              43.0   93.348837  32.816868  21.0  72.50   91.0  112.00
LA              35.0  110.200000  44.204604   9.0  89.00  115.0  150.50
MA              52.0   91.057692  36.152950  13.0  65.00   90.5  121.25
MD              60.0  101.033333  35.392217  18.0  75.75  104.0  123.50
ME              49.0   99.897959  45.576970  23.0  66.00  100.0  130.00
MI              58.0  101.431034  38.220557  30.0  74.50  102.0  127.75
MN              70.0  103.528571  41.182774  24.0  65.75  106.0  133.50
MO              51.0  103.686275  41.718337  20.0  79.50  103.0  133.50
MS              48.0  103.208333  40.469562  13.0  74.50  107.0  127.00
MT              53.0   90.132075  44.527018  10.0  58.00   85.0  121.00
NC              56.0  103.303571  39.160239  27.0  73.00  108.0  125.25
ND              44.0  107.045455  39.018752  35.0  80.50  101.0  145.25
NE              45.0  100.422222  39.768357  34.0  73.00   91.0  129.00
NH              43.0  102.348837  37.585385  13.0  83.00  105.0  124.50
NJ              50.0   98.960000  38.430409   1.0  72.50   95.5  133.50
NM              44.0  106.681818  39.750251  16.0  71.75  106.0  134.25
NV              61.0  104.409836  40.558344   3.0  78.00  105.0  136.00
NY              68.0   96.279412  46.200357   9.0  63.25   98.5  126.50
OH              66.0   98.590909  31.394746  29.0  75.00   97.5  123.00
OK              52.0  110.557692  44.154991  15.0  85.00  107.5  149.00
OR              62.0   99.870968  45.174156   6.0  64.75   98.5  135.00
PA              36.0  102.361111  35.674042  28.0  76.50   99.0  125.00
RI              48.0   96.625000  37.516309  17.0  73.75  101.0  120.25
SC              49.0   92.102041  42.793226   1.0  73.00   99.0  111.00
SD              49.0  106.816327  43.767222  20.0  87.00  110.0  128.00
TN              41.0   90.317073  39.564150   1.0  69.00   98.0  120.00
TX              55.0   92.400000  41.174246   1.0  68.00   90.0  124.00
UT              60.0   99.900000  42.726446   4.0  71.75   95.5  117.25
VA              67.0  105.850746  40.131320  10.0  85.50  108.0  134.50
VT              57.0  103.947368  34.546770  43.0  75.00  101.0  126.00
WA              48.0  103.145833  42.013670  40.0  62.75  106.5  136.00
WI              61.0   96.934426  36.769040  16.0  70.00   92.0  123.00
WV              88.0   94.465909  38.430995  11.0  66.25   92.0  123.25
WY              66.0  105.378788  40.969319  28.0  81.75  102.5  127.00

             Area code              ... Total intl charge        \
         max     count        mean  ...               75%   max
State                               ...
AK     177.0      43.0  442.255814  ...            3.2000  4.02
AL     200.0      66.0  429.939394  ...            3.2100  4.64
AR     179.0      47.0  437.468085  ...            3.2000  4.59
AZ     192.0      45.0  430.333333  ...            3.2700  4.29
CA     185.0      24.0  429.666667  ...            3.3825  4.81
CO     192.0      59.0  431.711864  ...            3.3200  4.86
CT     212.0      59.0  429.203390  ...            3.1600  4.67
DC     217.0      45.0  440.733333  ...            3.3200  4.46
DE     224.0      51.0  439.568627  ...            3.3500  4.56
FL     185.0      54.0  445.500000  ...            3.3075  4.75
GA     202.0      49.0  442.081633  ...            3.2400  4.19
HI     190.0      44.0  423.886364  ...            3.4800  4.37
IA     197.0      38.0  446.210526  ...            3.0150  3.59
ID     224.0      56.0  440.892857  ...            3.2900  5.10
IL     179.0      45.0  436.355556  ...            3.3500  4.91
IN     205.0      54.0  445.111111  ...            3.0500  4.35
KS     170.0      52.0  444.980769  ...            3.5400  4.35
KY     172.0      43.0  437.837209  ...            3.5100  4.51
LA     179.0      35.0  434.514286  ...            3.2000  3.67
MA     166.0      52.0  430.846154  ...            3.2750  4.32
MD     176.0      60.0  430.783333  ...            3.2975  4.86
ME     205.0      49.0  454.285714  ...            3.1300  5.40
MI     225.0      58.0  444.793103  ...            3.3650  4.83
MN     186.0      70.0  440.342857  ...            3.2625  4.59
MO     196.0      51.0  425.980392  ...            3.2550  4.02
MS     193.0      48.0  441.104167  ...            3.3350  4.21
MT     185.0      53.0  436.452830  ...            3.4000  4.16
NC     210.0      56.0  434.678571  ...            3.0125  4.56
ND     182.0      44.0  436.681818  ...            3.1225  4.43
NE     194.0      45.0  434.400000  ...            3.1100  4.91
NH     174.0      43.0  431.953488  ...            3.1900  4.21
NJ     162.0      50.0  437.880000  ...            3.5400  4.21
NM     188.0      44.0  430.204545  ...            3.2900  3.89
NV     183.0      61.0  441.770492  ...            3.1600  4.59
NY     204.0      68.0  430.014706  ...            3.1300  4.13
OH     164.0      66.0  434.575758  ...            3.2700  4.75
OK     194.0      52.0  436.730769  ...            3.3775  4.81
OR     190.0      62.0  438.048387  ...            3.3350  4.97
PA     176.0      36.0  439.444444  ...            3.1000  4.40
RI     190.0      48.0  449.604167  ...            3.0350  4.27
SC     212.0      49.0  436.693878  ...            3.1900  4.21
SD     221.0      49.0  442.510204  ...            3.1300  4.32
TN     176.0      41.0  436.634146  ...            3.2100  4.56
TX     201.0      55.0  432.090909  ...            3.4800  3.92
UT     243.0      60.0  440.633333  ...            3.1600  4.56
VA     210.0      67.0  436.805970  ...            3.4000  4.35
VT     193.0      57.0  439.947368  ...            3.2100  3.89
WA     184.0      48.0  436.125000  ...            3.1800  4.19
WI     184.0      61.0  436.409836  ...            2.9400  4.13
WV     177.0      88.0  442.954545  ...            3.1375  4.21
WY     225.0      66.0  436.439394  ...            3.3800  4.29

      Customer service calls
                       count      mean       std  min   25%  50%   75%  max
State
AK                      43.0  1.511628  1.241583  0.0  1.00  1.0  2.00  5.0
AL                      66.0  1.666667  1.450022  0.0  1.00  1.0  2.00  7.0
AR                      47.0  2.148936  1.654752  0.0  1.00  2.0  3.00  7.0
AZ                      45.0  1.377778  1.133957  0.0  1.00  1.0  2.00  4.0
CA                      24.0  1.416667  1.471960  0.0  0.00  1.0  2.00  5.0
CO                      59.0  1.830508  1.416072  0.0  1.00  1.0  3.00  6.0
CT                      59.0  1.406780  1.131350  0.0  1.00  1.0  2.00  4.0
DC                      45.0  1.288889  1.160373  0.0  0.00  1.0  2.00  5.0
DE                      51.0  1.705882  1.285210  0.0  1.00  2.0  2.00  5.0
FL                      54.0  1.611111  1.337650  0.0  0.25  1.0  3.00  5.0
GA                      49.0  1.918367  1.366820  0.0  1.00  2.0  3.00  5.0
HI                      44.0  1.727273  1.560615  0.0  1.00  1.0  2.00  7.0
IA                      38.0  1.605263  1.366382  0.0  1.00  1.0  2.00  5.0
ID                      56.0  1.642857  1.419713  0.0  1.00  1.0  3.00  6.0
IL                      45.0  1.111111  1.172065  0.0  0.00  1.0  2.00  4.0
IN                      54.0  1.611111  1.139624  0.0  1.00  1.0  2.00  5.0
KS                      52.0  1.480769  1.128775  0.0  1.00  1.0  2.00  4.0
KY                      43.0  1.744186  1.544468  0.0  1.00  2.0  2.00  7.0
LA                      35.0  1.514286  1.401080  0.0  1.00  1.0  2.00  6.0
MA                      52.0  1.230769  1.148151  0.0  0.00  1.0  2.00  4.0
MD                      60.0  1.650000  1.560367  0.0  0.00  1.0  3.00  6.0
ME                      49.0  1.734694  1.168609  0.0  1.00  2.0  2.00  4.0
MI                      58.0  1.586207  1.487191  0.0  1.00  1.0  2.00  7.0
MN                      70.0  1.514286  1.529828  0.0  1.00  1.0  2.00  9.0
MO                      51.0  1.529412  1.137593  0.0  1.00  1.0  2.00  5.0
MS                      48.0  1.687500  1.205594  0.0  1.00  1.0  2.25  5.0
MT                      53.0  1.584906  1.215825  0.0  1.00  1.0  2.00  6.0
NC                      56.0  1.535714  1.278697  0.0  0.75  1.5  2.00  5.0
ND                      44.0  1.500000  0.927613  0.0  1.00  1.0  2.00  4.0
NE                      45.0  1.622222  1.402739  0.0  1.00  1.0  3.00  6.0
NH                      43.0  1.627907  1.543392  0.0  1.00  1.0  2.00  8.0
NJ                      50.0  1.700000  1.656773  0.0  1.00  1.0  2.00  9.0
NM                      44.0  1.454545  0.975384  0.0  1.00  1.0  2.00  4.0
NV                      61.0  1.606557  1.187135  0.0  1.00  1.0  2.00  5.0
NY                      68.0  1.691176  1.395701  0.0  1.00  1.0  2.00  6.0
OH                      66.0  1.348485  1.270886  0.0  0.00  1.0  2.00  7.0
OK                      52.0  1.807692  1.314153  0.0  1.00  2.0  3.00  5.0
OR                      62.0  1.790323  1.269272  0.0  1.00  2.0  2.00  6.0
PA                      36.0  1.305556  1.237958  0.0  0.00  1.0  2.00  4.0
RI                      48.0  1.416667  1.318176  0.0  0.00  1.0  2.25  4.0
SC                      49.0  1.469388  1.355576  0.0  0.00  1.0  2.00  4.0
SD                      49.0  1.408163  1.059056  0.0  1.00  1.0  2.00  4.0
TN                      41.0  1.317073  1.233674  0.0  1.00  1.0  2.00  6.0
TX                      55.0  1.490909  1.289168  0.0  1.00  1.0  2.00  5.0
UT                      60.0  1.333333  1.174109  0.0  1.00  1.0  2.00  6.0
VA                      67.0  1.537313  1.247159  0.0  1.00  1.0  2.00  5.0
VT                      57.0  1.736842  1.552950  0.0  1.00  1.0  3.00  7.0
WA                      48.0  1.479167  1.288073  0.0  0.75  1.0  2.00  5.0
WI                      61.0  1.360656  1.080629  0.0  1.00  1.0  2.00  4.0
WV                      88.0  1.625000  1.253157  0.0  1.00  1.0  2.00  5.0
WY                      66.0  1.439394  1.229494  0.0  1.00  1.0  2.00  5.0

[51 rows x 128 columns]

In [174]:
#AGREGADO DE LA INFORMACIÓN
DATASET_AGRUPADO_STATE.agg(
    MAX_Acc_len = ("Account length","max") ,
    STD_Are_cod = ("Area code", "std") ,
    MEAN_NV_Messages = ("Number vmail messages","mean") ,
    VAR_TD_Minutes = ("Total day minutes", "var") ,
    SUM_TD_Calls = ("Total day calls", "sum") ,
    MIN_TD_Charge = ("Total day charge", "min"),
    Acc_len_25 = ("Account length", lambda X : X.quantile(0.25)) ,
    Acc_len_50 = ("Account length", lambda X : X.quantile(0.5)) , 
    Acc_len_75 = ("Account length", lambda X : X.quantile(0.75)) 
)

,MAX_Acc_len,STD_Are_cod,MEAN_NV_Messages,VAR_TD_Minutes,SUM_TD_Calls,MIN_TD_Charge,Acc_len_25,Acc_len_50,Acc_len_75
State,,,,,,,,,
AK,177,45.203820,7.255814,2562.676058,4069,9.89,66.00,104.0,127.00
AL,200,38.159132,6.742424,2464.621399,6563,14.76,78.25,95.5,121.75
AR,179,43.027216,5.659574,2869.223895,4906,9.40,79.50,98.0,115.00
AZ,192,37.571145,9.044444,1992.876646,4565,13.82,85.00,100.0,127.00
CA,185,36.791618,10.375000,1930.374493,2416,15.78,80.75,99.5,117.00
CO,192,40.021568,8.186441,3538.346365,5598,5.25,72.50,104.0,125.00
CT,212,36.936936,6.338983,3696.789474,5818,6.43,68.50,95.0,119.50
DC,217,44.737822,9.155556,2842.433768,4407,9.71,74.00,108.0,136.00
DE,224,43.841649,7.254902,2361.094729,5026,7.91,76.50,99.0,119.00
FL,185,46.104373,9.500000,3376.357987,5358,8.11,91.25,109.5,129.75
GA,202,45.671762,11.040816,2864.264430,5126,12.36,72.00,93.0,125.00
HI,190,31.341492,8.704545,3093.013953,4444,7.12,87.00,105.0,132.50
IA,197,46.688246,7.500000,2413.457383,3957,14.98,62.50,93.5,127.50
ID,224,44.178431,10.392857,2496.690792,6049,9.45,81.00,97.5,121.00
IL,179,42.463972,6.800000,2435.959222,4547,11.75,74.00,91.0,138.00
IN,205,46.393992,7.259259,2456.865521,5714,8.48,78.00,98.5,118.50
KS,170,45.820832,7.115385,3610.542093,5216,4.59,77.50,110.0,130.25
KY,172,42.897958,7.790698,3716.391063,4261,12.55,72.50,91.0,112.00
LA,179,41.801612,8.257143,1578.479378,3604,9.93,89.00,115.0,150.50
MA,166,39.126434,8.596154,2530.032172,5284,10.01,65.00,90.5,121.25
MD,176,37.959430,7.750000,3272.357568,5870,13.28,75.75,104.0,123.50
ME,205,48.817261,7.551020,2721.509583,4925,10.00,66.00,100.0,130.00
MI,225,45.984650,6.965517,3094.484952,5747,3.21,74.50,102.0,127.75
MN,186,44.465224,8.742857,3291.913839,6923,8.60,65.75,106.0,133.50
MO,196,33.988522,7.960784,3426.075200,5094,7.65,79.50,103.0,133.50
MS,193,44.764271,9.583333,3552.231910,4916,12.02,74.50,107.0,127.00
MT,185,42.430743,10.075472,2529.910733,5051,15.27,58.00,85.0,121.00
NC,210,41.902531,9.410714,3362.595221,5775,9.30,73.00,108.0,125.25
ND,182,42.924364,12.090909,2193.124693,4427,14.03,80.50,101.0,145.25
NE,194,40.969168,9.488889,2427.277071,4261,5.78,73.00,91.0,129.00
NH,174,40.751251,6.627907,3814.731351,4347,2.99,83.00,105.0,124.50
NJ,162,43.280594,9.640000,1940.522453,4968,19.55,72.50,95.5,133.50
NM,188,38.174982,6.068182,2254.964625,4474,11.75,71.75,106.0,134.25
NV,183,44.585645,6.393443,3210.809541,6241,11.46,78.00,105.0,136.00
NY,204,37.417169,7.088235,3284.258180,6744,10.30,63.25,98.5,126.50
OH,164,41.326862,10.515152,3396.887424,6586,1.33,75.00,97.5,123.00
OK,194,42.818411,8.269231,3876.420784,5190,0.44,85.00,107.5,149.00
OR,190,42.868624,5.854839,2830.674323,5863,2.13,64.75,98.5,135.00
PA,176,44.474355,8.250000,2538.300444,3560,17.85,76.50,99.0,125.00
RI,190,47.336612,7.458333,3405.319131,4842,6.87,73.75,101.0,120.25
SC,212,42.273516,8.367347,3793.461667,4977,3.32,73.00,99.0,111.00
SD,221,45.375802,9.367347,3268.507900,4602,0.00,87.00,110.0,128.00
TN,176,42.279283,7.365854,2399.224549,4086,17.53,69.00,98.0,120.00
TX,201,39.427511,6.290909,2946.426620,5568,14.40,68.00,90.0,124.00
UT,243,44.060808,9.166667,3036.062201,5981,10.74,71.75,95.5,117.25
VA,210,43.107420,6.656716,2302.664722,7096,13.79,85.50,108.0,134.50
VT,193,44.241795,6.526316,3036.075157,5759,0.00,75.00,101.0,126.00
WA,184,43.211811,4.166667,2892.932181,4825,6.41,62.75,106.5,136.00
WI,184,42.474846,8.196721,3469.736552,5917,1.34,70.00,92.0,123.00
WV,177,44.931854,8.988636,2796.376968,9196,10.40,66.25,92.0,123.25
WY,225,42.025314,7.030303,2478.391273,6688,14.06,81.75,102.5,127.00

## PARTE 18.15: AGRUPAR UN DATASET MEDIANTE 2+ VARIABLES

In [176]:
DATASET_AGRUPADO_STATE_INT = DATASET.groupby(["State","International plan"])
DATASET_AGRUPADO_STATE_INT

In [181]:
#FILTRAR LA INFORMACIÓN DE UN DATASET AGRUPADO
DATASET_AGRUPADO_STATE_INT.get_group(("KS","No")).head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
145,KS,70,408,No,No,0,232.1,122,39.46,292.3,112,24.85,201.2,112,9.05,0.0,0,0.00,3,False
231,KS,137,408,No,No,0,205.9,88,35.00,209.3,86,17.79,289.9,84,13.05,14.5,4,3.92,2,False
299,KS,132,415,No,No,0,83.4,110,14.18,232.2,137,19.74,146.7,114,6.60,7.6,5,2.05,1,False
308,KS,127,415,No,No,0,221.0,100,37.57,160.7,113,13.66,233.1,96,10.49,6.8,4,1.84,2,False

In [182]:
#AGRUPAR LA INFORMACIÓN CON BASE EN ALGUNA FUNCIÓN
DATASET_AGRUPADO_STATE_INT.mean()

                          Account length   Area code  Number vmail messages  \
State International plan
AK    No                       98.051282  440.179487               6.846154
      Yes                     127.500000  462.500000              11.250000
AL    No                       98.338983  428.728814               7.050847
      Yes                      96.000000  440.142857               4.142857
AR    No                       92.410256  439.820513               5.846154
...                                  ...         ...                    ...
WI    Yes                      93.333333  413.833333               5.666667
WV    No                       93.879518  442.349398               8.602410
      Yes                     104.200000  453.000000              15.400000
WY    No                      102.210526  436.614035               6.666667
      Yes                     125.444444  435.333333               9.333333

                          Total day minutes  Total day calls  \
State International plan
AK    No                         180.110256        95.384615
      Yes                        180.350000        87.250000
AL    No                         188.067797        98.813559
      Yes                        190.942857       104.714286
AR    No                         175.189744       105.076923
...                                     ...              ...
WI    Yes                        195.133333       100.500000
WV    No                         169.693976       104.024096
      Yes                        210.500000       112.400000
WY    No                         176.443860       100.087719
      Yes                        202.055556       109.222222

                          Total day charge  Total eve minutes  \
State International plan
AK    No                         30.619231         182.379487
      Yes                        30.660000         205.825000
AL    No                         31.971356         191.398305
      Yes                        32.460000         204.600000
AR    No                         29.782821         203.212821
...                                    ...                ...
WI    Yes                        33.171667         201.616667
WV    No                         28.848675         184.498795
      Yes                        35.786000         210.000000
WY    No                         29.995614         211.749123
      Yes                        34.348889         199.755556

                          Total eve calls  Total eve charge  \
State International plan
AK    No                        95.128205         15.502308
      Yes                       99.750000         17.497500
AL    No                        97.000000         16.268983
      Yes                      107.142857         17.391429
AR    No                        99.358974         17.273846
...                                   ...               ...
WI    Yes                      102.333333         17.140000
WV    No                        98.614458         15.682289
      Yes                      111.800000         17.850000
WY    No                        98.280702         17.998596
      Yes                      104.777778         16.980000

                          Total night minutes  Total night calls  \
State International plan
AK    No                           194.484615          97.358974
      Yes                          175.075000         105.000000
AL    No                           187.167797         101.355932
      Yes                          167.128571         100.142857
AR    No                           204.502564          95.897436
...                                       ...                ...
WI    Yes                          217.533333         113.333333
WV    No                           197.791566          99.963855
      Yes                          228.420000         113.200000
WY    No                           194.259649         101.789474
      Yes                          223.677778         109.111111

                          Total night charge  Total intl minutes  \
State International plan
AK    No                            8.751795           10.012821
      Yes                           7.880000           11.325000
AL    No                            8.422712           10.164407
      Yes                           7.520000           10.442857
AR    No                            9.202821           10.587179
...                                      ...                 ...
WI    Yes                           9.788333            9.600000
WV    No                            8.900964            9.857831
      Yes                          10.280000           10.820000
WY    No                            8.741579           10.387719
      Yes                          10.066667           10.044444

                          Total intl calls  Total intl charge  \
State International plan
AK    No                          4.923077           2.703333
      Yes                         4.500000           3.057500
AL    No                          4.593220           2.744407
      Yes                         5.571429           2.818571
AR    No                          4.923077           2.858718
...                                    ...                ...
WI    Yes                         4.166667           2.591667
WV    No                          4.373494           2.662048
      Yes                         4.400000           2.922000
WY    No                          4.947368           2.805088
      Yes                         4.777778           2.712222

                          Customer service calls     Churn
State International plan
AK    No                                1.487179  0.051282
      Yes                               1.750000  0.250000
AL    No                                1.677966  0.084746
      Yes                               1.571429  0.285714
AR    No                                2.153846  0.179487
...                                          ...       ...
WI    Yes                               1.666667  0.166667
WV    No                                1.626506  0.084337
      Yes                               1.600000  0.000000
WY    No                                1.508772  0.087719
      Yes                               1.000000  0.333333

[101 rows x 17 columns]

In [183]:
#TAMAÑO DE LA CATEGORÍA
DATASET_AGRUPADO_STATE_INT.size()

State  International plan
AK     No                    39
       Yes                    4
AL     No                    59
       Yes                    7
AR     No                    39
                             ..
WI     Yes                    6
WV     No                    83
       Yes                    5
WY     No                    57
       Yes                    9
Length: 101, dtype: int64

In [184]:
#DESCRIPCIÓN DE LA CATEGORÍA
DATASET_AGRUPADO_STATE_INT.describe()

                         Account length                                       \
                                  count        mean        std   min     25%
State International plan
AK    No                           39.0   98.051282  34.590802  41.0   66.00
      Yes                           4.0  127.500000  53.904236  51.0  114.75
AL    No                           59.0   98.338983  40.670081   8.0   79.50
      Yes                           7.0   96.000000  54.711364  19.0   75.50
AR    No                           39.0   92.410256  32.701777   5.0   77.50
...                                 ...         ...        ...   ...     ...
WI    Yes                           6.0   93.333333  37.945575  44.0   70.75
WV    No                           83.0   93.879518  38.899620  11.0   65.50
      Yes                           5.0  104.200000  31.268195  57.0   94.00
WY    No                           57.0  102.210526  40.335529  28.0   78.00
      Yes                           9.0  125.444444  41.527434  43.0  106.00

                                               Area code              ...  \
                            50%     75%    max     count        mean  ...
State International plan                                              ...
AK    No                  103.0  126.00  173.0      39.0  440.179487  ...
      Yes                 141.0  153.75  177.0       4.0  462.500000  ...
AL    No                   98.0  123.50  200.0      59.0  428.728814  ...
      Yes                  91.0  107.00  197.0       7.0  440.142857  ...
AR    No                   95.0  112.50  163.0      39.0  439.820513  ...
...                         ...     ...    ...       ...         ...  ...
WI    Yes                  88.5  117.50  147.0       6.0  413.833333  ...
WV    No                   90.0  123.50  177.0      83.0  442.349398  ...
      Yes                 112.0  117.00  141.0       5.0  453.000000  ...
WY    No                   97.0  124.00  225.0      57.0  436.614035  ...
      Yes                 127.0  157.00  185.0       9.0  435.333333  ...

                         Total intl charge       Customer service calls  \
                                       75%   max                  count
State International plan
AK    No                            3.2000  4.02                   39.0
      Yes                           3.1175  3.32                    4.0
AL    No                            3.2000  4.64                   59.0
      Yes                           3.4950  3.78                    7.0
AR    No                            3.2250  4.59                   39.0
...                                    ...   ...                    ...
WI    Yes                           2.6575  2.92                    6.0
WV    No                            3.1450  4.21                   83.0
      Yes                           3.0200  3.29                    5.0
WY    No                            3.3200  4.29                   57.0
      Yes                           3.4800  3.89                    9.0


                              mean       std  min   25%  50%   75%  max
State International plan
AK    No                  1.487179  1.274689  0.0  1.00  1.0  2.00  5.0
      Yes                 1.750000  0.957427  1.0  1.00  1.5  2.25  3.0
AL    No                  1.677966  1.407378  0.0  1.00  1.0  2.00  7.0
      Yes                 1.571429  1.902379  0.0  0.00  1.0  2.50  5.0
AR    No                  2.153846  1.581779  0.0  1.00  2.0  3.00  7.0
...                            ...       ...  ...   ...  ...   ...  ...
WI    Yes                 1.666667  1.632993  0.0  0.25  1.5  2.75  4.0
WV    No                  1.626506  1.246564  0.0  1.00  1.0  2.00  5.0
      Yes                 1.600000  1.516575  0.0  1.00  1.0  2.00  4.0
WY    No                  1.508772  1.269460  0.0  1.00  1.0  2.00  5.0
      Yes                 1.000000  0.866025  0.0  0.00  1.0  2.00  2.0

[101 rows x 128 columns]

In [185]:
#AGREGADO DE LA INFORMACIÓN
DATASET_AGRUPADO_STATE_INT.agg(
    MAX_Acc_len = ("Account length","max") ,
    STD_Are_cod = ("Area code", "std") ,
    MEAN_NV_Messages = ("Number vmail messages","mean") ,
    VAR_TD_Minutes = ("Total day minutes", "var") ,
    SUM_TD_Calls = ("Total day calls", "sum") ,
    MIN_TD_Charge = ("Total day charge", "min"),
    Acc_len_25 = ("Account length", lambda X : X.quantile(0.25)) ,
    Acc_len_50 = ("Account length", lambda X : X.quantile(0.5)) , 
    Acc_len_75 = ("Account length", lambda X : X.quantile(0.75)) 
)

                          MAX_Acc_len  STD_Are_cod  MEAN_NV_Messages  \
State International plan
AK    No                          173    44.423128          6.846154
      Yes                         177    54.848276         11.250000
AL    No                          200    37.164513          7.050847
      Yes                         197    47.824082          4.142857
AR    No                          163    44.658866          5.846154
...                               ...          ...               ...
WI    Yes                         147     2.857738          5.666667
WV    No                          177    44.759093          8.602410
      Yes                         141    52.033643         15.400000
WY    No                          225    42.343727          6.666667
      Yes                         185    42.393985          9.333333

                          VAR_TD_Minutes  SUM_TD_Calls  MIN_TD_Charge  \
State International plan
AK    No                     2583.661471          3720           9.89
      Yes                    3151.016667           349          22.61
AL    No                     2446.350497          5830          14.76
      Yes                    3043.389524           733          21.64
AR    No                     3103.254629          4098           9.40
...                                  ...           ...            ...
WI    Yes                    5375.514667           603          10.59
WV    No                     2801.885939          8634          10.40
      Yes                    1419.385000           562          27.52
WY    No                     2354.578221          5705          14.06
      Yes                    3017.557778           983          16.30

                          Acc_len_25  Acc_len_50  Acc_len_75
State International plan
AK    No                       66.00       103.0      126.00
      Yes                     114.75       141.0      153.75
AL    No                       79.50        98.0      123.50
      Yes                      75.50        91.0      107.00
AR    No                       77.50        95.0      112.50
...                              ...         ...         ...
WI    Yes                      70.75        88.5      117.50
WV    No                       65.50        90.0      123.50
      Yes                      94.00       112.0      117.00
WY    No                       78.00        97.0      124.00
      Yes                     106.00       127.0      157.00

[101 rows x 9 columns]

## PARTE 18.16: ORDENAR UN DATASET AGRUPADO

In [219]:
DATASET = DATASET.sort_values(["Total day minutes"],ascending = False).reset_index()
DATASET = DATASET.drop("index", axis = 1)

DATASET_AGRUPADO_STATE = DATASET.groupby(["State"])
DATASET_AGRUPADO_STATE

In [222]:
DATASET_AGRUPADO_STATE.get_group("KS") # .reset_index()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
11,KS,126,408,No,No,0,321.3,99,54.62,167.9,93,14.27,193.6,106,8.71,8.0,4,2.16,1,True
44,KS,110,415,Yes,No,0,293.3,79,49.86,188.5,90,16.02,266.9,91,12.01,14.5,4,3.92,0,True
140,KS,128,510,No,No,0,268.1,95,45.58,120.5,126,10.24,220.8,121,9.94,14.4,6,3.89,2,False
142,KS,110,415,Yes,Yes,27,267.9,103,45.54,263.3,74,22.38,178.1,106,8.01,8.3,2,2.24,1,True
150,KS,93,415,No,No,0,266.0,120,45.22,130.1,84,11.06,165.8,63,7.46,13.1,6,3.54,3,False
155,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
183,KS,107,415,No,No,0,260.5,108,44.29,102.4,110,8.70,129.7,148,5.84,9.8,5,2.65,1,False
257,KS,46,510,No,No,0,250.3,100,42.55,260.6,90,22.15,195.0,104,8.78,13.3,2,3.59,2,True
261,KS,131,415,No,Yes,28,249.6,87,42.43,227.2,138,19.31,239.9,92,10.80,7.6,3,2.05,3,False
285,KS,91,408,Yes,No,0,246.4,110,41.89,182.0,98,15.47,157.6,106,7.09,12.1,2,3.27,2,True
312,KS,24,510,No,No,0,243.0,91,41.31,183.9,77,15.63,184.3,109,8.29,15.3,6,4.13,0,True
353,KS,148,510,No,No,0,239.3,84,40.68,195.7,85,16.63,232.6,104,10.47,10.9,3,2.94,1,False
359,KS,164,510,No,Yes,30,238.8,100,40.60,230.0,121,19.55,206.3,66,9.28,13.2,8,3.56,1,False
423,KS,94,510,No,Yes,28,233.2,88,39.64,113.3,102,9.63,118.0,71,5.31,16.1,4,4.35,0,False
434,KS,70,408,No,No,0,232.1,122,39.46,292.3,112,24.85,201.2,112,9.05,0.0,0,0.00,3,False
437,KS,119,415,No,No,0,231.5,82,39.36,266.9,97,22.69,211.0,118,9.49,7.4,10,2.00,1,False
454,KS,137,415,No,No,0,230.2,113,39.13,220.4,79,18.73,204.7,111,9.21,10.7,7,2.89,4,False
501,KS,84,415,No,No,0,225.9,86,38.40,275.6,105,23.43,201.4,108,9.06,14.3,3,3.86,3,True
505,KS,86,408,No,Yes,23,225.5,107,38.34,246.3,105,20.94,245.7,81,11.06,9.8,2,2.65,0,False
542,KS,70,415,No,No,0,222.8,114,37.88,215.9,113,18.35,223.5,122,10.06,0.0,0,0.00,1,False
580,KS,127,415,No,No,0,221.0,100,37.57,160.7,113,13.66,233.1,96,10.49,6.8,4,1.84,2,False
634,KS,149,510,No,No,0,217.7,91,37.01,273.5,74,23.25,226.9,99,10.21,9.6,3,2.59,3,False
661,KS,117,510,No,Yes,25,216.0,140,36.72,224.1,69,19.05,267.9,112,12.06,11.8,4,3.19,0,False
793,KS,110,510,No,No,0,208.0,69,35.36,95.1,94,8.08,178.5,129,8.03,8.0,11,2.16,1,False
805,KS,68,415,No,No,0,207.6,68,35.29,251.6,123,21.39,191.6,100,8.62,10.9,6,2.94,2,False
845,KS,137,408,No,No,0,205.9,88,35.00,209.3,86,17.79,289.9,84,13.05,14.5,4,3.92,2,False
928,KS,57,415,No,Yes,37,201.2,76,34.20,280.1,122,23.81,154.2,110,6.94,11.8,1,3.19,1,False
950,KS,170,415,No,Yes,42,199.5,119,33.92,135.0,90,11.48,184.6,49,8.31,10.9,3,2.94,4,True
1053,KS,73,408,No,No,0,194.8,112,33.12,167.2,85,14.21,100.3,61,4.51,10.8,6,2.92,1,False
1126,KS,163,415,No,No,0,191.3,89,32.52,193.9,87,16.48,268.4,121,12.08,12.8,4,3.46,1,False
1127,KS,99,415,No,No,0,191.2,110,32.50,163.9,102,13.93,243.6,114,10.96,14.1,3,3.81,1,False
1157,KS,132,415,No,No,0,190.1,105,32.32,182.2,116,15.49,279.8,105,12.59,13.0,2,3.51,1,False
1216,KS,143,408,No,Yes,24,186.6,69,31.72,222.0,116,18.87,234.9,138,10.57,11.6,5,3.13,1,False
1246,KS,117,415,No,No,0,184.8,83,31.42,248.6,101,21.13,133.1,113,5.99,9.6,8,2.59,1,False
1361,KS,36,510,No,No,0,178.6,83,30.36,213.1,103,18.11,198.0,119,8.91,10.9,5,2.94,1,False
1372,KS,79,415,No,No,0,177.9,83,30.24,167.3,84,14.22,223.7,142,10.07,15.2,8,4.10,0,False
1428,KS,137,415,No,Yes,19,175.3,96,29.80,241.3,146,20.51,211.4,109,9.51,7.8,2,2.11,0,False
1603,KS,52,415,No,No,0,165.5,78,28.14,205.5,89,17.47,213.6,124,9.61,12.2,6,3.29,0,False
1639,KS,123,415,No,No,0,163.1,119,27.73,249.4,51,21.20,168.2,77,7.57,9.0,10,2.43,1,False
1677,KS,124,510,No,Yes,37,161.2,109,27.40,204.2,79,17.36,231.5,87,10.42,8.9,4,2.40,1,False
1712,KS,68,510,No,No,0,159.5,123,27.12,240.8,93,20.47,210.3,76,9.46,11.4,3,3.08,1,False
1730,KS,124,415,No,No,0,158.6,104,26.96,211.2,77,17.95,179.3,104,8.07,10.2,8,2.75,3,False
1813,KS,130,510,No,No,0,154.0,95,26.18,205.9,106,17.50,233.7,75,10.52,12.9,1,3.48,1,False
1981,KS,101,510,No,Yes,25,144.1,144,24.50,167.6,105,14.25,240.0,107,10.80,14.5,3,3.92,1,False
2055,KS,123,415,No,No,0,140.0,106,23.80,153.7,101,13.06,50.1,87,2.25,12.5,1,3.38,2,False
2170,KS,167,415,No,No,0,131.6,120,22.37,211.3,96,17.96,168.3,97,7.57,11.1,4,3.00,4,True
2202,KS,67,510,No,No,0,129.0,78,21.93,188.0,116,15.98,235.0,102,10.58,11.2,3,3.02,2,False
2353,KS,87,510,No,No,0,115.4,90,19.62,262.6,68,22.32,245.7,69,11.06,13.1,5,3.54,2,False
2565,KS,132,415,No,No,0,83.4,110,14.18,232.2,137,19.74,146.7,114,6.60,7.6,5,2.05,1,False
2612,KS,103,408,Yes,No,0,62.8,124,10.68,170.4,66,14.48,280.2,78,12.61,9.4,4,2.54,3,False
2643,KS,47,510,Yes,No,0,47.8,120,8.13,178.9,123,15.21,152.6,96,6.87,13.3,7,3.59,0,True
2656,KS,43,415,No,No,0,27.0,117,4.59,160.9,97,13.68,279.5,96,12.58,10.7,3,2.89,3,False

## PARTE 18.17: FILTRAR UN DATASET AGRUPADO

### APOYO PARA ENTENDER ESTE CAPÍTULO:

#### Filtrar en un DATASET agrupado no es lo mismo que filtrar sobre un DATASET sin agrupar 
#### Para entender lo anterior analiza estas 2 preguntas:
1. Dime los registros cuyo "Total day minutes" sea mayor a 185 (filtrado simple)
2. Dime los estados cuyo "Total day minutes" promedio sea mayor a 185 (filtrado sobre agrupado)

#### Para aplicar un filtrado sobre un DATASET agrupado es necesario tener en cuenta que responde a preguntas como la siguiente:
* Dime los registros cuyo "FUNCIÓN AGRUPADORA" de "VARIABLE AGRUPADORA" cumple "CONDICIÓN"

#### Paso a paso a seguir:
1. Implementa una agrupación del DATASET con base a la variable agrupadora
2. Sobre el DATASET agrupado aplica una función filter para aplicar la condición solicitada
3. Obtén los índices de dicha las filas que cumplen dicha condición
4. Filtra dichos índices de filas sobre el DATASET inicial

In [201]:
DATASET_AGRUPADO_STATE = DATASET.groupby(["State"])
DATASET_AGRUPADO_STATE

In [202]:
DATASET_AGRUPADO_STATE.mean()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,
AK,100.790698,442.255814,7.255814,180.132558,94.627907,30.623023,184.560465,95.558140,15.687907,192.679070,98.069767,8.670698,10.134884,4.883721,2.736279,1.511628,0.069767
AL,98.090909,429.939394,6.742424,188.372727,99.439394,32.023182,192.798485,98.075758,16.388030,185.042424,101.227273,8.326970,10.193939,4.696970,2.752273,1.666667,0.106061
AR,95.170213,437.468085,5.659574,174.695745,104.382979,29.698511,203.065957,99.787234,17.261277,201.572340,96.936170,9.071064,10.478723,4.829787,2.829362,2.148936,0.234043
AZ,103.111111,430.333333,9.044444,173.748889,101.444444,29.537556,185.053333,103.044444,15.729778,198.815556,100.466667,8.947333,10.615556,5.288889,2.866222,1.377778,0.066667
CA,100.458333,429.666667,10.375000,180.783333,100.666667,30.733750,199.179167,106.500000,16.930833,191.791667,100.125000,8.630417,10.150000,4.416667,2.742083,1.416667,0.208333
CO,101.983051,431.711864,8.186441,179.513559,94.881356,30.518136,208.579661,96.203390,17.728983,189.706780,95.576271,8.537627,9.777966,4.237288,2.640678,1.830508,0.118644
CT,94.457627,429.203390,6.338983,174.281356,98.610169,29.628136,203.991525,98.694915,17.339661,201.883051,101.915254,9.085254,9.949153,3.983051,2.686271,1.406780,0.186441
DC,105.866667,440.733333,9.155556,167.737778,97.933333,28.516222,197.697778,101.933333,16.805556,205.535556,97.000000,9.249333,10.782222,4.044444,2.912222,1.288889,0.111111
DE,99.941176,439.568627,7.254902,173.535294,98.549020,29.501961,209.711765,99.333333,17.825882,204.901961,101.705882,9.220588,10.350980,3.901961,2.795882,1.705882,0.156863
FL,109.777778,445.500000,9.500000,178.577778,99.222222,30.359259,206.142593,106.925926,17.522407,195.727778,100.740741,8.807407,9.938889,3.944444,2.683889,1.611111,0.129630
GA,100.653061,442.081633,11.040816,186.487755,104.612245,31.703673,204.273469,101.877551,17.363469,195.622449,105.795918,8.803061,10.357143,4.040816,2.797143,1.918367,0.163265
HI,105.090909,423.886364,8.704545,172.700000,101.000000,29.358182,190.920455,99.136364,16.227727,200.902273,98.295455,9.040227,10.075000,4.772727,2.720682,1.727273,0.045455
IA,94.500000,446.210526,7.500000,182.221053,104.131579,30.978684,202.544737,98.157895,17.216842,193.284211,98.736842,8.698684,9.747368,4.763158,2.632368,1.605263,0.078947
ID,102.642857,440.892857,10.392857,174.439286,108.017857,29.655179,194.644643,98.285714,16.545179,205.371429,100.392857,9.241964,10.371429,4.303571,2.800357,1.642857,0.089286
IL,101.022222,436.355556,6.800000,169.962222,101.044444,28.894889,202.617778,102.088889,17.222444,199.302222,97.311111,8.968667,10.288889,4.333333,2.778889,1.111111,0.088889
IN,101.851852,445.111111,7.259259,196.929630,105.814815,33.478889,199.359259,98.703704,16.945556,214.755556,100.388889,9.663889,9.775926,4.259259,2.639815,1.611111,0.111111
KS,105.211538,444.980769,7.115385,196.178846,100.307692,33.350962,202.917308,98.326923,17.248077,205.296154,100.384615,9.238462,10.901923,4.346154,2.944038,1.480769,0.192308
KY,93.348837,437.837209,7.790698,175.441860,99.093023,29.826047,194.406977,99.651163,16.524419,199.372093,102.720930,8.971860,10.851163,4.209302,2.930000,1.744186,0.139535
LA,110.200000,434.514286,8.257143,171.605714,102.971429,29.173143,193.802857,96.628571,16.474000,206.088571,101.628571,9.273714,9.148571,4.342857,2.471143,1.514286,0.085714
MA,91.057692,430.846154,8.596154,176.780769,101.615385,30.052885,216.250000,98.326923,18.381731,211.438462,96.730769,9.515385,9.986538,4.288462,2.696923,1.230769,0.153846
MD,101.033333,430.783333,7.750000,198.615000,97.833333,33.765333,194.415000,99.850000,16.525167,201.426667,95.600000,9.063833,10.740000,4.383333,2.900000,1.650000,0.233333
ME,99.897959,454.285714,7.551020,182.457143,100.510204,31.018776,201.148980,106.346939,17.097959,199.930612,97.306122,8.996939,9.957143,4.632653,2.689592,1.734694,0.224490
MI,101.431034,444.793103,6.965517,179.043103,99.086207,30.437241,208.812069,100.844828,17.748793,193.794828,103.603448,8.720345,10.550000,4.603448,2.848793,1.586207,0.224138
MN,103.528571,440.342857,8.742857,179.608571,98.900000,30.533857,198.757143,103.514286,16.894714,207.952857,101.642857,9.357857,10.418571,4.428571,2.813571,1.514286,0.185714
MO,103.686275,425.980392,7.960784,170.100000,99.882353,28.918235,203.794118,102.294118,17.322941,205.049020,101.372549,9.227059,10.235294,4.882353,2.764118,1.529412,0.098039
MS,103.208333,441.104167,9.583333,173.447917,102.416667,29.486667,196.972917,99.104167,16.743333,201.412500,99.791667,9.063333,10.437500,4.895833,2.818750,1.687500,0.229167
MT,90.132075,436.452830,10.075472,173.524528,95.301887,29.499245,199.288679,97.188679,16.940000,197.020755,102.547170,8.866038,10.696226,4.415094,2.888491,1.584906,0.188679
NC,103.303571,434.678571,9.410714,185.492857,103.125000,31.534286,199.871429,104.232143,16.989464,194.260714,100.464286,8.741607,10.003571,3.910714,2.701607,1.535714,0.160714
ND,107.045455,436.681818,12.090909,186.236364,100.613636,31.661136,202.361364,102.636364,17.201136,202.168182,102.636364,9.097500,9.334091,5.136364,2.521136,1.500000,0.090909
NE,100.422222,434.400000,9.488889,178.355556,94.688889,30.320222,201.860000,102.200000,17.157333,206.755556,103.444444,9.303778,10.728889,4.111111,2.897556,1.622222,0.088889
NH,102.348837,431.953488,6.627907,177.523256,101.093023,30.179070,197.834884,96.046512,16.816279,213.151163,98.302326,9.591628,10.434884,5.000000,2.817907,1.627907,0.209302
NJ,98.960000,437.880000,9.640000,199.086000,99.360000,33.844800,199.858000,101.380000,16.988000,203.962000,100.380000,9.178400,11.224000,4.800000,3.031800,1.700000,0.280000
NM,106.681818,430.204545,6.068182,173.684091,101.681818,29.526364,212.252273,102.340909,18.041818,202.263636,103.068182,9.101364,10.159091,4.795455,2.743864,1.454545,0.090909
NV,104.409836,441.770492,6.393443,177.750820,102.311475,30.218197,203.637705,95.918033,17.309344,208.237705,101.377049,9.370492,10.080328,4.213115,2.721803,1.606557,0.213115
NY,96.279412,430.014706,7.088235,172.686765,99.176471,29.357941,196.908824,100.911765,16.737353,204.125000,98.632353,9.186176,10.216176,4.764706,2.758382,1.691176,0.176471
OH,98.590909,434.575758,10.515152,184.689394,99.787879,31.398182,206.809091,101.363636,17.579091,208.325758,103.757576,9.374394,10.307576,4.439394,2.783788,1.348485,0.151515
OK,110.557692,436.730769,8.269231,180.000000,99.807692,30.600192,191.061538,105.057692,16.241154,196.678846,101.942308,8.850192,10.567308,4.769231,2.854615,1.807692,0.134615
OR,99.870968,438.048387,5.854839,170.375806,94.564516,28.964839,197.930645,98.564516,16.824677,199.708065,102.209677,8.987097,10.520968,4.403226,2.841774,1.790323,0.112903
PA,102.361111,439.444444,8.250000,196.211111,98.888889,33.356111,187.136111,100.361111,15.906111,193.302778,99.500000,8.699444,10.422222,3.583333,2.814167,1.305556,0.222222
RI,96.625000,449.604167,7.458333,174.270833,100.875000,29.627083,205.595833,93.270833,17.476042,206.770833,101.750000,9.304583,10.100000,4.479167,2.727083,1.416667,0.062500
SC,92.102041,436.693878,8.367347,162.528571,101.571429,27.630408,205.926531,100.714286,17.503265,193.306122,99.816327,8.698980,9.838776,4.102041,2.657143,1.469388,0.224490
SD,106.816327,442.510204,9.367347,191.404082,93.918367,32.538980,207.681633,98.367347,17.652653,201.644898,94.081633,9.074490,9.848980,4.306122,2.659184,1.408163,0.122449
TN,90.317073,436.634146,7.365854,182.846341,99.658537,31.084390,207.348780,105.853659,17.625122,205.580488,91.000000,9.251707,10.429268,4.243902,2.815854,1.317073,0.121951
TX,92.400000,432.090909,6.290909,181.030909,101.236364,30.776182,197.910909,101.254545,16.822727,200.496364,99.290909,9.022545,10.585455,4.709091,2.858727,1.490909,0.290909
UT,99.900000,440.633333,9.166667,183.568333,99.683333,31.207000,196.346667,97.866667,16.690000,192.546667,100.733333,8.664167,9.976667,4.616667,2.694000,1.333333,0.133333
VA,105.850746,436.805970,6.656716,179.073134,105.910448,30.442537,204.835821,100.462687,17.411791,212.667164,93.104478,9.570448,10.564179,4.671642,2.852687,1.537313,0.059701
VT,103.947368,439.947368,6.526316,183.114035,101.035088,31.130351,202.252632,96.982456,17.192105,207.229825,103.578947,9.325088,10.080702,4.736842,2.722105,1.736842,0.105263
WA,103.145833,436.125000,4.166667,175.462500,100.520833,29.829375,204.029167,95.750000,17.342708,199.016667,103.750000,8.956042,9.712500,4.520833,2.622708,1.479167,0.208333
WI,96.934426,436.409836,8.196721,175.775410,97.000000,29.881803,197.759016,99.081967,16.810000,198.313115,98.426230,8.924262,9.634426,4.114754,2.601639,1.360656,0.065574
WV,94.465909,442.954545,8.988636,172.012500,104.500000,29.242841,185.947727,99.363636,15.805455,199.531818,100.715909,8.979318,9.912500,4.375000,2.676818,1.625000,0.079545
WY,105.378788,436.439394,7.030303,179.936364,101.333333,30.589242,210.113636,99.166667,17.859697,198.271212,102.787879,8.922273,10.340909,4.924242,2.792424,1.439394,0.121212

In [239]:
#FILTRADO MEDIANTE LA CONDICIÓN (PROMEDIO DE Total day minutes > 199)
INDICES_FILAS = DATASET_AGRUPADO_STATE["Total day minutes"].filter(lambda X: X.mean() > 199).index
DATASET.loc[INDICES_FILAS , : ]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
29,NJ,88,415,No,No,0,301.5,136,51.26,257.7,72,21.90,132.9,118,5.98,13.4,2,3.62,4,True
52,NJ,60,408,No,No,0,289.8,101,49.27,255.6,115,21.73,242.8,76,10.93,11.7,4,3.16,2,True
152,NJ,24,408,No,No,0,265.6,86,45.15,208.8,102,17.75,182.5,105,8.21,11.1,6,3.00,2,True
202,NJ,46,408,No,No,0,257.4,67,43.76,261.1,91,22.19,204.4,107,9.20,13.4,5,3.62,2,True
226,NJ,147,415,No,Yes,36,254.2,78,43.21,228.1,105,19.39,98.0,125,4.41,13.8,7,3.73,5,False
266,NJ,75,415,No,Yes,42,248.9,93,42.31,170.8,108,14.52,104.5,91,4.70,11.2,8,3.02,1,False
295,NJ,127,510,No,No,0,245.2,91,41.68,217.2,92,18.46,243.1,128,10.94,13.9,6,3.75,0,True
308,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
330,NJ,138,408,No,No,0,241.8,93,41.11,170.5,83,14.49,295.3,104,13.29,11.8,7,3.19,3,False
362,NJ,128,415,No,No,0,237.9,125,40.44,247.6,93,21.05,208.9,68,9.40,13.9,4,3.75,1,True
376,NJ,85,415,No,No,0,236.9,93,40.27,197.7,113,16.80,309.1,78,13.91,11.4,7,3.08,2,True
440,NJ,78,415,No,No,0,231.0,115,39.27,230.4,140,19.58,261.4,120,11.76,9.5,3,2.57,1,False
441,NJ,139,415,No,Yes,43,231.0,85,39.27,222.3,82,18.90,148.0,105,6.66,8.3,5,2.24,2,False
442,NJ,74,415,No,No,0,230.9,93,39.25,223.0,78,18.96,157.8,101,7.10,9.7,2,2.62,3,False
471,NJ,53,408,No,No,0,228.6,117,38.86,132.8,123,11.29,227.2,124,10.22,10.1,2,2.73,9,True
504,NJ,93,510,Yes,Yes,38,225.7,117,38.37,119.6,122,10.17,193.2,125,8.69,14.0,7,3.78,1,True
514,NJ,59,510,Yes,Yes,31,225.0,78,38.25,191.3,79,16.26,226.7,79,10.20,9.1,3,2.46,1,False
537,NJ,87,510,No,No,0,223.2,109,37.94,127.5,86,10.84,289.3,83,13.02,14.5,4,3.92,3,False
593,NJ,138,510,No,No,0,220.2,89,37.43,88.3,125,7.51,195.3,79,8.79,12.9,5,3.48,0,False
594,NJ,95,408,Yes,Yes,37,220.2,109,37.43,185.3,99,15.75,205.1,82,9.23,4.1,2,1.11,0,True
635,NJ,162,408,No,No,0,217.6,87,36.99,279.0,71,23.72,250.7,65,11.28,10.4,4,2.81,2,True
796,NJ,106,415,No,No,0,207.9,91,35.34,172.0,109,14.62,191.8,143,8.63,14.4,7,3.89,4,False
887,NJ,100,415,No,No,0,203.8,122,34.65,283.1,76,24.06,197.3,83,8.88,12.5,3,3.38,0,False
922,NJ,135,510,No,Yes,28,201.4,100,34.24,246.5,117,20.95,154.8,131,6.97,12.9,4,3.48,2,True
1049,NJ,59,510,No,No,0,195.0,58,33.15,198.5,88,16.87,304.3,110,13.69,14.8,9,4.00,0,False
1076,NJ,153,415,No,No,0,193.8,90,32.95,195.3,121,16.60,182.7,108,8.22,8.5,3,2.30,1,False
1103,NJ,156,408,No,Yes,27,192.3,137,32.69,199.9,115,16.99,244.2,112,10.99,14.8,8,4.00,1,False
1152,NJ,84,415,No,No,0,190.2,102,32.33,197.7,141,16.80,247.5,102,11.14,9.8,6,2.65,2,False
1195,NJ,136,408,No,Yes,27,187.7,84,31.91,221.0,147,18.79,145.7,110,6.56,10.0,4,2.70,3,False
1198,NJ,93,415,Yes,Yes,20,187.5,110,31.88,169.8,94,14.43,175.3,127,7.89,12.1,4,3.27,1,False
1225,NJ,113,415,No,No,0,186.0,55,31.62,237.4,105,20.18,148.1,83,6.66,12.2,6,3.29,1,False
1281,NJ,1,415,No,Yes,30,183.1,95,31.13,232.6,110,19.77,248.3,110,11.17,8.4,2,2.27,0,False
1319,NJ,42,408,Yes,No,0,180.7,127,30.72,174.6,94,14.84,165.3,114,7.44,12.0,6,3.24,2,False
1389,NJ,111,510,No,No,0,176.9,128,30.07,102.8,56,8.74,213.7,84,9.62,10.5,2,2.84,4,True
1419,NJ,72,415,No,No,0,175.5,103,29.84,132.3,120,11.25,242.9,96,10.93,11.8,3,3.19,1,False
1438,NJ,66,415,No,Yes,16,174.7,92,29.70,232.1,105,19.73,305.4,98,13.74,8.9,2,2.40,1,False
1491,NJ,108,415,No,Yes,41,171.6,110,29.17,136.1,78,11.57,183.4,103,8.25,10.8,7,2.92,0,False
1551,NJ,129,415,No,No,0,168.4,117,28.63,217.1,129,18.45,81.6,100,3.67,11.8,7,3.19,1,False
1628,NJ,42,415,No,Yes,32,163.8,80,27.85,177.8,123,15.11,190.4,106,8.57,8.1,5,2.19,0,False
1647,NJ,64,510,No,No,0,162.6,83,27.64,152.3,109,12.95,57.5,122,2.59,14.2,3,3.83,1,False
1711,NJ,123,408,No,No,0,159.5,77,27.12,303.8,92,25.82,226.9,120,10.21,12.0,4,3.24,0,False
1877,NJ,96,510,No,No,0,150.0,122,25.50,218.5,116,18.57,212.4,89,9.56,9.8,1,2.65,3,False
1943,NJ,122,415,No,Yes,34,146.4,104,24.89,89.7,103,7.62,220.0,91,9.90,15.6,4,4.21,2,False
1945,NJ,93,415,No,No,0,146.3,85,24.87,216.6,95,18.41,233.0,82,10.49,11.5,3,3.11,0,False
1977,NJ,88,510,No,No,0,144.3,116,24.53,156.4,74,13.29,214.7,90,9.66,7.8,10,2.11,3,False
2051,NJ,149,408,No,No,0,140.4,94,23.87,271.8,92,23.10,188.3,108,8.47,11.1,9,3.00,1,False
2161,NJ,113,408,No,No,0,132.1,72,22.46,247.5,107,21.04,246.2,123,11.08,6.9,6,1.86,3,False
2281,NJ,153,510,No,No,0,122.5,145,20.83,273.3,103,23.23,197.8,71,8.90,8.0,3,2.16,2,False
2314,NJ,151,415,No,No,0,118.9,128,20.21,278.3,65,23.66,194.8,61,8.77,13.2,10,3.56,2,False
2358,NJ,57,510,Yes,No,0,115.0,65,19.55,122.3,96,10.40,245.0,75,11.03,6.4,1,1.73,0,True