# PARTE 20: DIVISIÓN DEL DATASET

## PARTE 20.1: DIVIDIR EL DATASET CON DISTRIBUCIÓN NORMAL

In [1]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [2]:
DATASET.shape[0]

print("80%-->", int(0.8 * DATASET.shape[0]))
print("20%-->", int(0.2 * DATASET.shape[0]))

80%--> 2132
20%--> 533

In [3]:
import numpy as np

#GENERAMOS UNA LISTA NORMAL QUE SE ASIGNARÁ A UNA COLUMNA DEL DATASET
LISTA_NORMAL = np.random.randn(DATASET.shape[0])
DATASET["NORMAL"] = LISTA_NORMAL

#CALCULAR EL PERCENTIL 80% (ES PARA SABER DÓNDE DIVIDIR)
LIMITE = np.quantile(LISTA_NORMAL,0.8)

#ANÁLISIS DE PERTENENCIA A DATASET ENTRENAMIENTO (80%) O PRUEBAS (20%)
LISTA_CONDICION = LISTA_NORMAL < LIMITE
DATASET["CONDICION"] = LISTA_CONDICION

#GENERAR DATASET ENTRENAMIENTO Y PRUEBAS
DATASET_ENTRENAMIENTO = DATASET[DATASET["CONDICION"] == True]
DATASET_PRUEBA = DATASET[DATASET["CONDICION"] == False]

In [4]:
DATASET_ENTRENAMIENTO

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,NORMAL,CONDICION
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,...,244.7,91,11.01,10.0,3,2.70,1,False,0.521858,True
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,...,254.4,103,11.45,13.7,3,3.70,1,False,-1.207775,True
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,...,196.9,89,8.86,6.6,7,1.78,2,False,-1.762296,True
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,...,186.9,121,8.41,10.1,3,2.73,3,False,-0.882740,True
5,AL,118,510,Yes,No,0,223.4,98,37.98,220.6,...,203.9,118,9.18,6.3,6,1.70,0,False,-0.171131,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,SC,79,415,No,No,0,134.7,98,22.90,189.7,...,221.4,128,9.96,11.8,5,3.19,2,False,-0.200604,True
2662,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,...,279.1,83,12.56,9.9,6,2.67,2,False,-0.101687,True
2663,WV,68,415,No,No,0,231.1,57,39.29,153.4,...,191.3,123,8.61,9.6,4,2.59,3,False,-1.235629,True
2664,RI,28,510,No,No,0,180.8,109,30.74,288.8,...,191.9,91,8.64,14.1,6,3.81,2,False,-0.437543,True
2665,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,...,241.4,77,10.86,13.7,4,3.70,0,False,0.182862,True

In [5]:
DATASET_PRUEBA

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,NORMAL,CONDICION
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,...,162.6,104,7.32,12.2,5,3.29,0,False,1.827320,False
14,VT,93,510,No,No,0,190.7,114,32.42,218.2,...,129.6,121,5.83,8.1,3,2.19,3,False,2.003129,False
23,MT,54,408,No,No,0,134.3,73,22.83,155.5,...,102.1,68,4.59,14.7,4,3.97,3,False,1.054748,False
25,IL,142,415,No,No,0,84.8,95,14.42,136.7,...,250.5,148,11.27,14.2,6,3.83,2,False,1.733256,False
27,LA,172,408,No,No,0,212.0,121,36.04,31.2,...,293.3,78,13.20,12.6,10,3.40,3,False,1.060304,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2645,VT,100,408,Yes,No,0,219.4,112,37.30,225.7,...,255.3,95,11.49,12.0,4,3.24,4,False,3.163254,False
2646,NY,94,415,No,No,0,190.4,91,32.37,92.0,...,224.8,108,10.12,13.6,17,3.67,2,False,0.948458,False
2651,ME,149,415,No,Yes,18,148.5,106,25.25,114.5,...,178.3,98,8.02,6.5,4,1.76,0,False,0.873160,False
2656,GA,122,510,Yes,No,0,140.0,101,23.80,196.4,...,120.1,133,5.40,9.7,4,2.62,4,True,2.890705,False
2658,IN,117,415,No,No,0,118.4,126,20.13,249.3,...,227.0,56,10.22,13.6,3,3.67,5,True,1.488529,False

## PARTE 20.2: DIVIDIR EL DATASET CON SHUFFLE

In [6]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [10]:
from sklearn.utils import shuffle

#REVOLOTEADO EL DATASET
DATASET = shuffle(DATASET)

#CALCULAMOS LA FILA DE CORTE
FILA_CORTE = int(DATASET.shape[0] * 0.8)

#GENERAR DATASET ENTRENAMIENTO Y PRUEBAS
DATASET_ENTRENAMIENTO = DATASET[:FILA_CORTE]
DATASET_PRUEBA = DATASET[FILA_CORTE:]

In [11]:
DATASET_ENTRENAMIENTO

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
2397,NY,131,408,Yes,No,0,122.3,83,20.79,118.8,94,10.10,147.9,95,6.66,13.7,3,3.70,3,True
2322,HI,135,415,No,No,0,190.9,44,32.45,161.4,109,13.72,231.9,100,10.44,8.4,2,2.27,1,False
178,FL,93,415,No,No,0,151.4,89,25.74,186.4,76,15.84,172.5,120,7.76,10.9,3,2.94,0,False
985,TN,98,415,No,No,0,162.8,65,27.68,185.0,109,15.73,219.5,104,9.88,6.0,3,1.62,2,False
430,NE,194,408,No,No,0,48.4,101,8.23,281.1,138,23.89,218.5,87,9.83,18.2,1,4.91,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,CO,121,408,Yes,No,0,167.7,94,28.51,93.7,121,7.96,241.3,115,10.86,13.4,1,3.62,3,True
1473,WA,63,408,No,No,0,211.7,107,35.99,271.7,77,23.09,203.3,108,9.15,7.4,7,2.00,0,False
1873,UT,110,415,No,No,0,271.1,108,46.09,237.0,122,20.15,239.9,122,10.80,9.8,5,2.65,2,True
1532,PA,119,408,No,No,0,260.1,101,44.22,256.5,68,21.80,229.1,89,10.31,10.0,2,2.70,1,True
1077,VA,94,415,Yes,No,0,235.6,131,40.05,194.8,107,16.56,170.6,93,7.68,8.6,4,2.32,1,False

In [12]:
DATASET_PRUEBA

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
15,VA,76,510,No,Yes,33,189.7,66,32.25,212.8,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False
1217,ME,99,415,No,No,0,222.4,102,37.81,185.8,89,15.79,237.7,81,10.70,12.0,8,3.24,2,False
110,AR,163,408,No,No,0,197.0,109,33.49,202.6,128,17.22,206.4,80,9.29,9.1,10,2.46,1,False
2476,MS,190,415,Yes,No,0,111.9,55,19.02,223.0,124,18.96,243.2,81,10.94,10.0,7,2.70,3,False
1958,MT,97,415,No,Yes,15,117.6,97,19.99,196.3,126,16.69,157.4,113,7.08,6.4,3,1.73,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1854,FL,106,510,No,No,0,159.6,94,27.13,276.8,118,23.53,223.5,65,10.06,8.8,3,2.38,0,False
2213,PA,61,408,No,Yes,40,105.0,78,17.85,180.6,100,15.35,174.1,115,7.83,10.2,2,2.75,2,True
2466,WV,113,510,No,No,0,72.5,88,12.33,204.0,112,17.34,117.9,118,5.31,6.6,3,1.78,1,False
1963,MA,101,415,No,Yes,21,238.0,88,40.46,209.6,84,17.82,233.0,95,10.49,10.0,5,2.70,2,False
2564,SD,30,415,No,No,0,247.4,107,42.06,175.9,76,14.95,287.4,90,12.93,11.3,2,3.05,0,False

## PARTE 20.3: DIVIDIR EL DATASET CON TRAIN_TEST_SPLIT

In [13]:
import pandas as pd
RUTA = "DATASETS - CERTIFICACIÓN/17_1_VISUALIZACION_CHURN_MODEL.csv"
DATASET = pd.read_csv(RUTA)
DATASET.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [15]:
from sklearn.model_selection import train_test_split

DATASET_ENTRENAMIENTO , DATASET_PRUEBA  = train_test_split(DATASET , test_size = 0.2)

In [16]:
DATASET_ENTRENAMIENTO

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
2200,NJ,156,408,No,Yes,27,192.3,137,32.69,199.9,115,16.99,244.2,112,10.99,14.8,8,4.00,1,False
2194,HI,101,415,No,Yes,24,114.1,95,19.40,161.5,86,13.73,176.3,90,7.93,13.0,9,3.51,2,False
96,MO,112,510,No,Yes,36,113.7,117,19.33,157.5,82,13.39,177.6,118,7.99,10.0,3,2.70,2,False
339,SD,128,408,No,Yes,34,142.3,73,24.19,194.8,79,16.56,239.3,81,10.77,16.0,6,4.32,1,False
2303,CA,75,415,No,Yes,19,210.3,90,35.75,241.8,87,20.55,215.7,102,9.71,13.1,3,3.54,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,IL,44,415,No,Yes,34,221.8,105,37.71,161.7,85,13.74,227.7,62,10.25,14.0,7,3.78,0,False
2392,NY,46,415,No,No,0,122.2,67,20.77,167.2,62,14.21,194.8,98,8.77,9.7,6,2.62,1,False
485,MO,112,415,No,No,0,335.5,77,57.04,212.5,109,18.06,265.0,132,11.93,12.7,8,3.43,2,True
758,AL,91,510,No,Yes,23,232.4,97,39.51,186.0,88,15.81,190.5,128,8.57,12.3,3,3.32,3,False
304,AZ,90,415,No,No,0,179.2,77,30.46,210.7,99,17.91,276.9,58,12.46,9.2,6,2.48,2,False

In [17]:
DATASET_PRUEBA

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
799,MO,168,415,No,Yes,42,97.4,57,16.56,203.6,98,17.31,173.9,124,7.83,11.4,2,3.08,2,False
2244,MS,78,415,No,No,0,87.7,74,14.91,214.8,58,18.26,201.3,147,9.06,10.8,6,2.92,1,False
97,NE,46,408,No,No,0,210.2,92,35.73,227.3,77,19.32,200.1,116,9.00,13.1,7,3.54,1,False
683,OH,119,415,No,Yes,27,220.1,128,37.42,268.2,133,22.80,146.5,80,6.59,11.1,3,3.00,0,False
103,MS,162,415,No,No,0,70.7,108,12.02,157.5,87,13.39,154.8,82,6.97,9.1,3,2.46,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516,IL,65,510,No,No,0,192.0,89,32.64,139.5,88,11.86,187.4,102,8.43,5.5,4,1.49,2,False
1107,MO,86,415,No,No,0,125.5,139,21.34,269.8,93,22.93,235.8,110,10.61,8.9,8,2.40,1,False
787,TN,70,510,No,No,0,126.3,99,21.47,141.6,106,12.04,255.9,96,11.52,9.6,2,2.59,0,False
2650,MO,89,415,No,No,0,178.7,81,30.38,233.7,74,19.86,131.9,120,5.94,9.1,4,2.46,1,False
2268,NH,146,510,No,No,0,115.6,77,19.65,213.6,100,18.16,218.4,72,9.83,10.7,6,2.89,1,False